//! Conformance suite — the Tauri port of atlet SyncAdapter contract v1.1
//! (apps/atlet/spec/adapter.md), Track A4 of the arxa integration plan
//! (docs/plans/nostos-integration-tauri-flutter-push.md).
//!
//! Checklist mapping (the adapter.md 5 items, ported to the Tauri surface):
//! 1. init → subscribe → write → serverAcked fires < 60s
//!    (item 1, mapped: init = connect; serverAcked derived from a SECOND
//!    client read path — the spine echo WriteBack fans out to every live
//!    subscriber, so a row the observer can see MUST have round-tripped
//!    through the server. Never the writer own local apply.)
//! 2. Row injected server-side (POST /push) appears < 60s (item 2,
//!    remoteVisible — same derivation: observer read path).
//! 3. setConnected(false) → 25 writes → setConnected(true) → all 25
//!    serverAcked (item 3, mapped: the Tauri offline toggle is
//!    abort_subscribe()/subscribe() — the outbox holds the 25 and drains
//!    on reconnect; serverAcked again via the observer, one per row).
//! 4. signOut wipes (item 4): local rows gone from disk on reopen. The
//!    "re-init cold-syncs from zero" half needs server history replay,
//!    which the spine deliberately lacks (live-subscriber fan-out only) —
//!    that half rides the A5 real-server gate. Honest split, documented.
//! 5. No engine types leak (item 5): the JS surface (guest-js) is the
//!    app-facing layer — asserted statically: only @tauri-apps/api imports,
//!    and every registered Rust command has its camelCase JS counterpart.
//!
//! 6. (nostos addition, multi-table lift 2026-09-21) a write to the SECOND
//!    configured table round-trips through the server on the one socket
//!    (`plugins.cairn.tables` → `extra_tables`), and the primary table is
//!    untouched by it.
//!
//! Plus rail integrity (the subscribe-gap class): the four ACL edit points
//! (build.rs list, generate_handler!, default.toml, autogenerated command
//! files) must agree — a command missing from any one compiles green but is
//! rejected at runtime.
//!
//! Marks follow the adapter.md fairness rule: derived ONLY from data visible
//! through the normal read path (observer query), never engine-internal
//! callbacks or private state.
//!
//! NOTE: unlike the flutter suite prerequisites, this port needs NO
//! operator-provisioned environment — the spine is the live backend (real
//! production sync_handler + wire codec + FanOutService, no docker). That
//! closes the "conformance ran without a live backend" gap the plan C3 note
//! records for the flutter pilot.

mod common;

use common::{
    http_push, observer, observer_tables, poll_rows_with_prefix, poll_table_rows_with_prefix,
    spawn_spine,
};
use std::time::Duration;
use tauri_plugin_cairn::NostosState;

/// Item 1: connect → subscribe → write → the row round-trips through the
/// server (observer sees it) within the 60s contract ceiling.
#[tokio::test(flavor = "multi_thread")]
async fn item1_write_round_trips_through_server() {
    let (port, mut child) = spawn_spine().await;
    let obs = observer(port, "item1").await;

    let state = writer_state(port, "item1").await;
    state.subscribe("tasks".into()).await.expect("subscribe");
    tokio::time::sleep(Duration::from_millis(300)).await;
    state
        .write(
            "tasks".into(),
            "upsert".into(),
            "conf-item1".into(),
            Some(r#"{"title":"from-tauri","status":"open","priority":"5"}"#.into()),
        )
        .await
        .expect("write");

    let n = poll_rows_with_prefix(&obs, "conf-item1", 1, Duration::from_secs(60)).await;
    assert!(
        n >= 1,
        "serverAcked mark never fired: observer saw {n} rows for conf-item1"
    );
    println!("[conf] ITEM1_OK serverAcked via observer");
    let _ = child.kill().await;
}

/// Item 2: a server-side injected row (POST /push) appears on the observer
/// read path (remoteVisible) within the 60s ceiling.
#[tokio::test(flavor = "multi_thread")]
async fn item2_server_push_appears_on_read_path() {
    let (port, mut child) = spawn_spine().await;
    let obs = observer(port, "item2").await;

    http_push(
        port,
        r#"{"pk":"conf-item2","payload":{"title":"from-server","status":"open","priority":"5"}}"#,
    )
    .await;

    let n = poll_rows_with_prefix(&obs, "conf-item2", 1, Duration::from_secs(60)).await;
    assert!(
        n >= 1,
        "remoteVisible mark never fired: observer saw {n} rows for conf-item2"
    );
    println!("[conf] ITEM2_OK remoteVisible via observer");
    let _ = child.kill().await;
}

/// Item 3: the offline queue-drain run. 25 writes while disconnected (no
/// subscribe), then reconnect — the outbox drains in order and every row
/// round-trips (observer sees all 25). The 25-row count matches the frozen
/// flutter contract.
#[tokio::test(flavor = "multi_thread")]
async fn item3_offline_writes_drain_on_reconnect() {
    let (port, mut child) = spawn_spine().await;
    let obs = observer(port, "item3").await;

    // Connect but do NOT subscribe: no run loop, so the session is offline.
    // write() still succeeds — durable-local (ADR-0013 outbox contract).
    let state = writer_state(port, "item3").await;
    for i in 0..25 {
        state
            .write(
                "tasks".into(),
                "upsert".into(),
                format!("conf-item3-{i:02}"),
                Some(format!(
                    r#"{{"title":"offline {i}","status":"open","priority":"5"}}"#
                )),
            )
            .await
            .expect("offline write");
    }

    // Reconnect: subscribe spawns run_once, which flushes the pending queue
    // after the subscribe-ack (client.rs outbox contract).
    state.subscribe("tasks".into()).await.expect("resubscribe");

    let n = poll_rows_with_prefix(&obs, "conf-item3-", 25, Duration::from_secs(60)).await;
    assert_eq!(
        n, 25,
        "expected all 25 offline writes serverAcked, observer saw {n}"
    );
    println!("[conf] ITEM3_OK 25/25 drained + acked");
    let _ = child.kill().await;
}

/// Item 4: signOut wipes — the local store is emptied ON DISK (reopen sees
/// zero rows). The cold-resync half needs server history (the spine has
/// none); it rides the A5 real-server gate.
#[tokio::test(flavor = "multi_thread")]
async fn item4_sign_out_wipes_local_store() {
    let (port, mut child) = spawn_spine().await;
    let db = std::env::temp_dir().join(format!(
        "nostos-tauri-conf-item4-{}.sqlite",
        std::process::id()
    ));
    let _ = std::fs::remove_file(&db);
    let path = db.to_str().expect("utf8").to_owned();

    let state = NostosState::new();
    state
        .connect(
            Some(format!("ws://127.0.0.1:{port}/sync")),
            None,
            Some(path.clone()),
        )
        .await
        .expect("connect");
    state
        .write(
            "tasks".into(),
            "upsert".into(),
            "conf-item4".into(),
            Some(r#"{"title":"pre-signout"}"#.into()),
        )
        .await
        .expect("write");
    state.sign_out().await.expect("sign_out");

    // Reopen the SAME file: zero rows survive (the cross-user-leak guard).
    state
        .connect(
            Some(format!("ws://127.0.0.1:{port}/sync")),
            None,
            Some(path.clone()),
        )
        .await
        .expect("reconnect");
    let rows_json = state
        .query("SELECT pk FROM cairn_data WHERE table_name = 'tasks'".into())
        .await
        .expect("query after wipe");
    let rows: serde_json::Value = serde_json::from_str(&rows_json).expect("parse");
    assert!(
        rows.as_array().is_some_and(|a| a.is_empty()),
        "signOut must wipe the store, got: {rows_json}"
    );
    println!("[conf] ITEM4_OK local wipe verified on disk");
    let _ = std::fs::remove_file(&db);
    let _ = child.kill().await;
}

/// Item 5 + rail integrity: static pins that need no server.
mod surface {
    use std::collections::BTreeSet;
    use std::path::PathBuf;

    fn manifest(p: &str) -> String {
        let base = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        std::fs::read_to_string(base.join(p)).unwrap_or_else(|e| panic!("read {p}: {e}"))
    }

    /// The command list from build.rs (the slice inside Builder::new(&[...])).
    fn build_rs_commands() -> BTreeSet<String> {
        let src = manifest("build.rs");
        let start = src
            .find("tauri_plugin::Builder::new(&[")
            .expect("build.rs Builder::new slice");
        let rest = &src[start..];
        let end = rest.find("])").expect("build.rs slice end");
        rest[..end]
            .lines()
            .filter_map(|l| l.split('"').nth(1).map(str::to_owned))
            .collect()
    }

    /// The command list from generate_handler![...] in src/lib.rs. Entries
    /// are bare identifiers (no quotes), one per line, trailing comma.
    fn handler_commands() -> BTreeSet<String> {
        let src = manifest("src/lib.rs");
        let start = src
            .find("generate_handler![")
            .expect("generate_handler! in lib.rs");
        let rest = &src[start..];
        let end = rest.find("])").expect("handler list end");
        rest[..end]
            .lines()
            .skip(1) // the generate_handler![ line itself
            .filter_map(|l| {
                let t = l.trim().trim_end_matches(',');
                let ok = !t.is_empty() && t.chars().all(|c| c.is_alphanumeric() || c == '_');
                ok.then(|| t.to_owned())
            })
            .collect()
    }

    /// The allow-<cmd> grants from permissions/default.toml.
    fn default_toml_commands() -> BTreeSet<String> {
        let src = manifest("permissions/default.toml");
        src.lines()
            .filter_map(|l| l.trim().strip_prefix("\"allow-"))
            .map(|l| {
                l.trim_end_matches(',')
                    .trim_end_matches('"')
                    .replace('-', "_")
            })
            .collect()
    }

    /// One autogenerated <cmd>.toml per command (the tauri-plugin build
    /// script emits these from the build.rs list).
    fn autogenerated_command_files() -> BTreeSet<String> {
        let dir =
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("permissions/autogenerated/commands");
        std::fs::read_dir(&dir)
            .expect("autogenerated commands dir")
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().is_some_and(|x| x == "toml"))
            .filter_map(|e| {
                e.path()
                    .file_stem()
                    .map(|s| s.to_string_lossy().into_owned())
            })
            .collect()
    }

    /// The subscribe-gap class: a command registered in ONE of the four ACL
    /// edit points but not the others compiles green and fails at runtime
    /// with an ACL rejection. This test fails at edit time instead.
    #[test]
    fn acl_edit_points_stay_in_lockstep() {
        let build_rs = build_rs_commands();
        let handlers = handler_commands();
        let toml = default_toml_commands();
        let files = autogenerated_command_files();
        assert!(!build_rs.is_empty(), "parse produced an empty build.rs set");
        assert_eq!(
            build_rs, handlers,
            "generate_handler! and build.rs disagree — a command here is IPC-reachable but not permission-generated (or vice versa)"
        );
        assert_eq!(
            build_rs, toml,
            "permissions/default.toml and build.rs disagree — a command here fails the ACL at runtime while everything compiles",
        );
        assert_eq!(
            build_rs, files,
            "autogenerated/commands/ and build.rs disagree — rerun the build to regenerate, or the build.rs list drifted",
        );
    }

    /// Item 5: no engine types leak into the app-facing JS surface. The
    /// guest-js package is the app layer; its only external import may be
    /// @tauri-apps/api — any nostos Rust/engine import would be a leak (the
    /// Tauri analogue of the flutter "no engine types in the app/bench
    /// layer" rule). Also pins the JS↔Rust surface lockstep: every
    /// registered command has its camelCase JS method in index.d.ts.
    #[test]
    fn js_surface_leaks_no_engine_types_and_covers_every_command() {
        for file in ["guest-js/index.js", "guest-js/index.d.ts"] {
            let src = manifest(file);
            for line in src.lines().filter(|l| l.trim_start().starts_with("import")) {
                assert!(
                    line.contains("@tauri-apps/api"),
                    "{file} imports something other than @tauri-apps/api: {line}"
                );
            }
        }

        // Surface lockstep: build.rs snake_case command → camelCase JS name.
        let dts = manifest("guest-js/index.d.ts");
        for cmd in build_rs_commands() {
            let camel = snake_to_camel(&cmd);
            assert!(
                dts.contains(&camel),
                "command {cmd} has no JS binding (expected a \"{camel}\" mention in guest-js/index.d.ts)",
            );
        }
    }

    fn snake_to_camel(s: &str) -> String {
        let mut out = String::with_capacity(s.len());
        let mut upper_next = false;
        for c in s.chars() {
            if c == '_' {
                upper_next = true;
            } else if upper_next {
                out.extend(c.to_uppercase());
                upper_next = false;
            } else {
                out.push(c);
            }
        }
        out
    }
}

/// Item 6 (multi-table): writer + observer both run `tables = ["tasks",
/// "notes"]`; a `notes` write is seen by the observer in `notes` (server
/// round-trip over the one socket) and never leaks into `tasks`.
#[tokio::test(flavor = "multi_thread")]
async fn item6_second_table_round_trips_through_server() {
    let (port, mut child) = spawn_spine().await;
    let obs = observer_tables(port, "item6", &["tasks", "notes"]).await;

    let state = observer_tables(port, "item6-writer", &["tasks", "notes"]).await;
    state
        .write(
            "notes".into(),
            "upsert".into(),
            "conf-item6".into(),
            Some(r#"{"body":"second-table"}"#.into()),
        )
        .await
        .expect("write to the second table");

    let n =
        poll_table_rows_with_prefix(&obs, "notes", "conf-item6", 1, Duration::from_secs(60)).await;
    assert!(n >= 1, "observer never saw the notes row: {n}");
    let leaked =
        poll_table_rows_with_prefix(&obs, "tasks", "conf-item6", 1, Duration::from_millis(500))
            .await;
    assert_eq!(leaked, 0, "notes row leaked into tasks");
    println!("[conf] ITEM6_OK second table round-trips");
    let _ = child.kill().await;
}

/// A connected (but NOT subscribed) writer client on its own temp DB.
async fn writer_state(port: u16, tag: &str) -> NostosState {
    let state = NostosState::new();
    let db = std::env::temp_dir().join(format!(
        "nostos-tauri-conf-writer-{tag}-{}.sqlite",
        std::process::id()
    ));
    let _ = std::fs::remove_file(&db);
    state
        .connect(
            Some(format!("ws://127.0.0.1:{port}/sync")),
            None,
            Some(db.to_str().expect("utf8").to_owned()),
        )
        .await
        .expect("writer connect");
    state
}
