// The direct-mode doorbell for a device that is not listening.
//
// `cairn.wake_absent_devices()` (generated by `nostos link --mode direct
// --push <url>`) posts `{"scope": "<claim>:<value>"}` here whenever a change
// lands for a scope with no awake device. This function looks the scope's push
// tokens up and sends ONE data-only message per token.
//
// Deploy:  supabase functions deploy cairn-push --no-verify-jwt
// Secrets: NOSTOS_PUSH_SECRET  (must equal cairn.push_config.secret)
//          SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY   (injected by the platform)
//          FCM_SERVICE_ACCOUNT  (the service-account JSON, as one line)
//
// `--no-verify-jwt` is deliberate and is why the shared secret is not
// optional: pg_net posts machine-to-machine and has no user JWT to present, so
// the bearer check below is the ONLY thing standing between this endpoint and
// anyone who learns the URL. `nostos doctor --mode direct` fails if the secret
// is unset.
//
// The payload carries no data — only "there is something for you". The device
// wakes, pulls through `cairn_pull`, and RLS decides what it may see. A
// doorbell that carried rows would be a second, unauthorized read path.

import { createClient } from "jsr:@supabase/supabase-js@2";

const FCM_SCOPE = "https://www.googleapis.com/auth/firebase.messaging";

Deno.serve(async (req: Request): Promise<Response> => {
  const secret = Deno.env.get("NOSTOS_PUSH_SECRET");
  if (!secret || req.headers.get("authorization") !== `Bearer ${secret}`) {
    return new Response("forbidden", { status: 403 });
  }

  const { scope } = await req.json();
  if (typeof scope !== "string" || scope.length === 0) {
    return new Response("missing scope", { status: 400 });
  }

  const db = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    { db: { schema: "cairn" } },
  );
  const { data: tokens, error } = await db
    .from("push_tokens")
    .select("platform, token")
    .eq("scope", scope);
  if (error) return new Response(error.message, { status: 500 });
  if (!tokens?.length) return new Response("no tokens", { status: 200 });

  const accessToken = await mintFcmToken();
  const project = JSON.parse(Deno.env.get("FCM_SERVICE_ACCOUNT")!).project_id;

  // Data-only, high priority: the OS wakes the app, the app pulls. A
  // notification-only message would render a banner and never run code.
  const results = await Promise.allSettled(
    tokens.filter((t) => t.platform === "fcm").map((t) =>
      fetch(`https://fcm.googleapis.com/v1/projects/${project}/messages:send`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message: {
            token: t.token,
            data: { cairn: "ring" },
            android: { priority: "HIGH" },
            apns: {
              headers: { "apns-priority": "5", "apns-push-type": "background" },
              payload: { aps: { "content-available": 1 } },
            },
          },
        }),
      })
    ),
  );

  const sent = results.filter((r) => r.status === "fulfilled").length;
  return Response.json({ scope, sent, of: tokens.length });
});

/// OAuth2 JWT-bearer flow for the FCM HTTP v1 API — the service account signs
/// an assertion, Google exchanges it for a one-hour access token.
async function mintFcmToken(): Promise<string> {
  const sa = JSON.parse(Deno.env.get("FCM_SERVICE_ACCOUNT")!);
  const now = Math.floor(Date.now() / 1000);
  const claims = {
    iss: sa.client_email,
    scope: FCM_SCOPE,
    aud: "https://oauth2.googleapis.com/token",
    iat: now,
    exp: now + 3600,
  };
  const enc = (o: unknown) =>
    btoa(JSON.stringify(o)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
  const unsigned = `${enc({ alg: "RS256", typ: "JWT" })}.${enc(claims)}`;

  const pem = sa.private_key.replace(/-----[^-]+-----|\s/g, "");
  const key = await crypto.subtle.importKey(
    "pkcs8",
    Uint8Array.from(atob(pem), (c) => c.charCodeAt(0)),
    { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = new Uint8Array(
    await crypto.subtle.sign("RSASSA-PKCS1-v1_5", key, new TextEncoder().encode(unsigned)),
  );
  const assertion = `${unsigned}.${
    btoa(String.fromCharCode(...sig)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "")
  }`;

  const res = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "urn:ietf:params:oauth:grant-type:jwt-bearer",
      assertion,
    }),
  });
  if (!res.ok) throw new Error(`FCM token exchange failed: ${await res.text()}`);
  return (await res.json()).access_token;
}
