// The direct-mode doorbell for a device that is not listening.
//
// `nostos.wake_absent_devices()` (generated by `nostos link --mode direct
// --push <url>`) posts `{"scope": "<claim>:<value>"}` here whenever a change
// lands for a scope with no awake device. This function looks the scope's push
// tokens up and sends ONE data-only message per token.
//
// Deploy:  supabase functions deploy nostos-push --no-verify-jwt
// Secrets: NOSTOS_PUSH_SECRET  (must equal nostos.push_config.secret)
//          SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY   (injected by the platform)
//          FCM_SERVICE_ACCOUNT  (the service-account JSON, as one line)
//
// `--no-verify-jwt` is deliberate and is why the shared secret is not
// optional: pg_net posts machine-to-machine and has no user JWT to present, so
// the bearer check below is the ONLY thing standing between this endpoint and
// anyone who learns the URL. `nostos doctor --mode direct` fails if the secret
// is unset.
//
// The doorbell carries no data — only "there is something for you". The device
// wakes, pulls through `nostos_pull`, and RLS decides what it may see. A
// doorbell that carried rows would be a second, unauthorized read path.
//
// The exception is a table the operator gave a template in
// `nostos.push_templates` (ADR-0037 §2): iOS never wakes a user-quit app for a
// silent push, so there the push IS the notification. The trigger posts the
// template and the changed row; only the filled-in title/body/route leave for
// Apple/Google, and only to the tokens of the scope the row was logged under.

import { createClient } from "jsr:@supabase/supabase-js@2";

const FCM_SCOPE = "https://www.googleapis.com/auth/firebase.messaging";
const LEGACY_SECRET = "CAIRN_PUSH_SECRET"; // rename:hold — pre-rename secret name, read as fallback until 1.0 (ADR-0046)

Deno.serve(async (req: Request): Promise<Response> => {
  const secret = Deno.env.get("NOSTOS_PUSH_SECRET") ?? Deno.env.get(LEGACY_SECRET);
  if (!secret || req.headers.get("authorization") !== `Bearer ${secret}`) {
    return new Response("forbidden", { status: 403 });
  }

  const { scope, row, title, body, category, route, options } = await req.json();
  if (typeof scope !== "string" || scope.length === 0) {
    return new Response("missing scope", { status: 400 });
  }

  // Read the registry through `public.nostos_push_targets`, NOT through
  // `nostos.push_tokens`. The `nostos` schema is deliberately not exposed to the
  // Data API — Supabase exposes `public, graphql_public` and nothing else — so
  // `{ db: { schema: "nostos" } }` here fails with `500 Invalid schema: nostos`
  // and no notification is ever sent. Found against a real Supabase stack.
  const db = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );
  const { data: tokens, error } = await db.rpc("nostos_push_targets", {
    p_scope: scope,
  });
  if (error) return new Response(error.message, { status: 500 });
  if (!tokens?.length) return new Response("no tokens", { status: 200 });

  const accessToken = await mintFcmToken();
  const project = JSON.parse(Deno.env.get("FCM_SERVICE_ACCOUNT")!).project_id;

  // No template: data-only, high priority — the OS wakes the app, the app
  // pulls. A notification-only message would render a banner and never run code.
  const message = title
    ? visible(
      fill(title, row),
      fill(body, row),
      category,
      route && fill(route, row),
      fillOptions(options, row),
    )
    : {
      data: { nostos: "ring" },
      android: { priority: "HIGH" },
      apns: {
        headers: { "apns-priority": "5", "apns-push-type": "background" },
        payload: { aps: { "content-available": 1 } },
      },
    };
  const results = await Promise.allSettled(
    tokens.filter((t) => t.platform === "fcm").map(async (t) => {
      const res = await fetch(`https://fcm.googleapis.com/v1/projects/${project}/messages:send`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ message: { token: t.token, ...message } }),
      });
      // fetch resolves on a 4xx too: an UNREGISTERED token is not a send.
      if (!res.ok) throw new Error(`${res.status} ${(await res.text()).slice(0, 200)}`);
    }),
  );

  const errors = results.flatMap((r) => r.status === "rejected" ? [String(r.reason)] : []);
  return Response.json({ scope, sent: results.length - errors.length, of: tokens.length, errors });
});

/// `{col}` → that column of the changed row, as server mode's
/// NOSTOS_PUSH_TABLES templates do.
function fill(template: string, row: Record<string, unknown> | null): string {
  return template.replace(/\{(\w+)\}/g, (_, col) => String(row?.[col] ?? ""));
}

/// `[k=v,…]` presentation options (ADR-0047), `{col}` filled like the title.
/// One whose column came back empty is dropped, as the server-mode router does.
function fillOptions(
  options: Record<string, string> | null | undefined,
  row: Record<string, unknown> | null,
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(options ?? {})) {
    const filled = fill(String(v), row);
    if (filled) out[k] = filled;
  }
  return out;
}

/// The options that need the app's Notification Service Extension, and the
/// keys they ride under (crates/nostos-infra/src/push/mod.rs `NSE_KEYS`).
const NSE_KEYS: [string, string][] = [
  ["image", "nostos_image"],
  ["sender", "nostos_sender"],
  ["avatar", "nostos_avatar"],
];

const ANDROID_PRIORITY: Record<string, string> = {
  passive: "PRIORITY_LOW",
  active: "PRIORITY_DEFAULT",
  "time-sensitive": "PRIORITY_HIGH",
  critical: "PRIORITY_MAX",
};

/// The FCM v1 shapes of crates/nostos-infra/src/push/fcm.rs, so a direct-mode
/// app renders exactly what a server-mode one did — options included.
function visible(
  title: string,
  body: string,
  category: string | undefined,
  route: string | undefined,
  options: Record<string, string>,
) {
  const data: Record<string, string> = route ? { nostos_route: route } : {};
  // deno-lint-ignore no-explicit-any
  let message: any;
  if (category) {
    // Action push: iOS draws `aps.alert` with the app-registered category's
    // buttons, killed app included. Android gets no `notification` block, so
    // the HIGH data message reaches the app, which posts it with the actions
    // — every option rides along as `nostos_<key>` for it to render.
    const extra = Object.fromEntries(Object.entries(options).map(([k, v]) => [`nostos_${k}`, v]));
    message = {
      data: { ...data, ...extra, title, body, category },
      android: { priority: "HIGH", ttl: "3600s" },
      apns: { payload: { aps: { alert: { title, body }, sound: "default", category } } },
    };
  } else {
    for (const [k, wire] of NSE_KEYS) if (options[k]) data[wire] = options[k];
    const notification: Record<string, unknown> = {
      channel_id: options.channel ?? "nostos",
      default_sound: !options.sound || options.sound === "default",
      vibrate_timings: ["0s", "0.3s", "0.2s", "0.3s"],
    };
    if (options.image) notification.image = options.image;
    if (options.collapse) notification.tag = options.collapse;
    if (options.level) notification.notification_priority = ANDROID_PRIORITY[options.level];
    if (options.sound && !["default", "none"].includes(options.sound)) {
      notification.sound = options.sound;
    }
    message = {
      notification: { title, body },
      data,
      android: { priority: "HIGH", ttl: "3600s", notification },
      apns: { payload: { aps: { sound: "default" } } },
    };
  }
  if (options.collapse) message.android.collapse_key = options.collapse;
  // The iOS half — crates/nostos-infra/src/push/mod.rs `apply_ios_options`.
  const aps = message.apns.payload.aps;
  if (options.subtitle) aps.alert = { title, body, subtitle: options.subtitle };
  if (options.thread) aps["thread-id"] = options.thread;
  if (options.level) aps["interruption-level"] = options.level;
  if (options.relevance) aps["relevance-score"] = Number(options.relevance);
  if (options.sound === "none") delete aps.sound;
  else if (options.sound) aps.sound = options.sound;
  for (const [k, wire] of NSE_KEYS) {
    if (options[k]) {
      message.apns.payload[wire] = options[k];
      aps["mutable-content"] = 1;
    }
  }
  if (options.image) message.apns.fcm_options = { image: options.image };
  if (options.collapse) {
    message.apns.headers = {
      "apns-collapse-id": [...options.collapse].filter((c) => c > " " && c <= "~").join("")
        .slice(0, 64),
    };
  }
  return message;
}

/// OAuth2 JWT-bearer flow for the FCM HTTP v1 API — the service account signs
/// an assertion, Google exchanges it for a one-hour access token.
async function mintFcmToken(): Promise<string> {
  const sa = JSON.parse(Deno.env.get("FCM_SERVICE_ACCOUNT")!);
  const now = Math.floor(Date.now() / 1000);
  const claims = {
    iss: sa.client_email,
    scope: FCM_SCOPE,
    aud: "https://oauth2.googleapis.com/token",
    iat: now,
    exp: now + 3600,
  };
  const enc = (o: unknown) =>
    btoa(JSON.stringify(o)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
  const unsigned = `${enc({ alg: "RS256", typ: "JWT" })}.${enc(claims)}`;

  const pem = sa.private_key.replace(/-----[^-]+-----|\s/g, "");
  const key = await crypto.subtle.importKey(
    "pkcs8",
    Uint8Array.from(atob(pem), (c) => c.charCodeAt(0)),
    { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = new Uint8Array(
    await crypto.subtle.sign("RSASSA-PKCS1-v1_5", key, new TextEncoder().encode(unsigned)),
  );
  const assertion = `${unsigned}.${
    btoa(String.fromCharCode(...sig)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "")
  }`;

  const res = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "urn:ietf:params:oauth:grant-type:jwt-bearer",
      assertion,
    }),
  });
  if (!res.ok) throw new Error(`FCM token exchange failed: ${await res.text()}`);
  return (await res.json()).access_token;
}
