// GENERATED by `nostos gen` — do not edit. Regenerate with `nostos pull && nostos gen`.
import 'package:nostos_flutter/nostos_flutter.dart';

const nostosConfig = NostosConfig(
  url: 'ws://127.0.0.1:8800/sync',
);

const nostosSchema = NostosSchema(tables: [
  NostosTable(name: 'tasks', primaryKey: ['id'], columns: [
    NostosColumn.text('id'),
    NostosColumn.text('org_id'),
    NostosColumn.text('assignee_id'),
    NostosColumn.text('title'),
    NostosColumn.integer('completed'),
    NostosColumn.text('created_at'),
    NostosColumn.text('updated_at'),
  ]),
  NostosTable(name: 'providers', primaryKey: ['id'], columns: [
    NostosColumn.text('id'),
    NostosColumn.text('name'),
    NostosColumn.text('specialty'),
    NostosColumn.text('email'),
    NostosColumn.text('phone'),
    NostosColumn.text('created_at'),
    NostosColumn.text('rate_type'),
    NostosColumn.text('hourly_rate_cents'),
    NostosColumn.text('flat_rate_cents'),
    NostosColumn.text('subscription_rate_cents'),
    NostosColumn.text('bio'),
    NostosColumn.text('avatar_color'),
  ]),
  NostosTable(name: 'clients', primaryKey: ['id'], columns: [
    NostosColumn.text('id'),
    NostosColumn.text('name'),
    NostosColumn.text('email'),
    NostosColumn.text('phone'),
    NostosColumn.text('notes'),
    NostosColumn.text('created_at'),
  ]),
  NostosTable(name: 'availabilities', primaryKey: ['id'], columns: [
    NostosColumn.text('id'),
    NostosColumn.text('provider_id'),
    NostosColumn.integer('weekday'),
    NostosColumn.integer('start_min'),
    NostosColumn.integer('end_min'),
  ]),
  NostosTable(name: 'appointments', primaryKey: ['id'], columns: [
    NostosColumn.text('id'),
    NostosColumn.text('provider_id'),
    NostosColumn.text('client_id'),
    NostosColumn.text('starts_at'),
    NostosColumn.integer('duration_min'),
    NostosColumn.text('status'),
    NostosColumn.text('notes'),
    NostosColumn.text('created_at'),
  ]),
  NostosTable(name: 'invoices', primaryKey: ['id'], columns: [
    NostosColumn.text('id'),
    NostosColumn.text('appointment_id'),
    NostosColumn.text('client_id'),
    NostosColumn.integer('amount_cents'),
    NostosColumn.text('status'),
    NostosColumn.text('issued_at'),
    NostosColumn.text('created_at'),
    NostosColumn.text('provider_id'),
    NostosColumn.text('line_type'),
    NostosColumn.text('rate_cents'),
    NostosColumn.text('hours_min'),
    NostosColumn.text('description'),
    NostosColumn.text('due_at'),
    NostosColumn.text('paid_at'),
  ]),
  NostosTable(name: 'messages', primaryKey: ['id'], columns: [
    NostosColumn.text('id'),
    NostosColumn.text('provider_id'),
    NostosColumn.text('client_id'),
    NostosColumn.text('sender_type'),
    NostosColumn.text('sender_id'),
    NostosColumn.text('body'),
    NostosColumn.text('created_at'),
    NostosColumn.text('read_at'),
  ]),
]);

class Task {
  const Task({required this.id, this.orgId, this.assigneeId, this.title, this.completed, this.createdAt, this.updatedAt});
  final String id;
  final String? orgId;
  final String? assigneeId;
  final String? title;
  final int? completed;
  final String? createdAt;
  final String? updatedAt;

  factory Task.fromRow(Map<String, dynamic> r) => Task(
    id: (r['_pk'] ?? r['id']).toString(),
    orgId: r['org_id']?.toString(),
    assigneeId: r['assignee_id']?.toString(),
    title: r['title']?.toString(),
    completed: r['completed'] is int ? r['completed'] : int.tryParse('${r['completed']}'),
    createdAt: r['created_at']?.toString(),
    updatedAt: r['updated_at']?.toString(),
  );

  Map<String, dynamic> toPayload() => {
    'id': id,
    'org_id': orgId,
    'assignee_id': assigneeId,
    'title': title,
    'completed': completed,
    'created_at': createdAt,
    'updated_at': updatedAt,
  };
}

class Provider {
  const Provider({required this.id, this.name, this.specialty, this.email, this.phone, this.createdAt, this.rateType, this.hourlyRateCents, this.flatRateCents, this.subscriptionRateCents, this.bio, this.avatarColor});
  final String id;
  final String? name;
  final String? specialty;
  final String? email;
  final String? phone;
  final String? createdAt;
  final String? rateType;
  final String? hourlyRateCents;
  final String? flatRateCents;
  final String? subscriptionRateCents;
  final String? bio;
  final String? avatarColor;

  factory Provider.fromRow(Map<String, dynamic> r) => Provider(
    id: (r['_pk'] ?? r['id']).toString(),
    name: r['name']?.toString(),
    specialty: r['specialty']?.toString(),
    email: r['email']?.toString(),
    phone: r['phone']?.toString(),
    createdAt: r['created_at']?.toString(),
    rateType: r['rate_type']?.toString(),
    hourlyRateCents: r['hourly_rate_cents']?.toString(),
    flatRateCents: r['flat_rate_cents']?.toString(),
    subscriptionRateCents: r['subscription_rate_cents']?.toString(),
    bio: r['bio']?.toString(),
    avatarColor: r['avatar_color']?.toString(),
  );

  Map<String, dynamic> toPayload() => {
    'id': id,
    'name': name,
    'specialty': specialty,
    'email': email,
    'phone': phone,
    'created_at': createdAt,
    'rate_type': rateType,
    'hourly_rate_cents': hourlyRateCents,
    'flat_rate_cents': flatRateCents,
    'subscription_rate_cents': subscriptionRateCents,
    'bio': bio,
    'avatar_color': avatarColor,
  };
}

class Client {
  const Client({required this.id, this.name, this.email, this.phone, this.notes, this.createdAt});
  final String id;
  final String? name;
  final String? email;
  final String? phone;
  final String? notes;
  final String? createdAt;

  factory Client.fromRow(Map<String, dynamic> r) => Client(
    id: (r['_pk'] ?? r['id']).toString(),
    name: r['name']?.toString(),
    email: r['email']?.toString(),
    phone: r['phone']?.toString(),
    notes: r['notes']?.toString(),
    createdAt: r['created_at']?.toString(),
  );

  Map<String, dynamic> toPayload() => {
    'id': id,
    'name': name,
    'email': email,
    'phone': phone,
    'notes': notes,
    'created_at': createdAt,
  };
}

class Availability {
  const Availability({required this.id, this.providerId, this.weekday, this.startMin, this.endMin});
  final String id;
  final String? providerId;
  final int? weekday;
  final int? startMin;
  final int? endMin;

  factory Availability.fromRow(Map<String, dynamic> r) => Availability(
    id: (r['_pk'] ?? r['id']).toString(),
    providerId: r['provider_id']?.toString(),
    weekday: r['weekday'] is int ? r['weekday'] : int.tryParse('${r['weekday']}'),
    startMin: r['start_min'] is int ? r['start_min'] : int.tryParse('${r['start_min']}'),
    endMin: r['end_min'] is int ? r['end_min'] : int.tryParse('${r['end_min']}'),
  );

  Map<String, dynamic> toPayload() => {
    'id': id,
    'provider_id': providerId,
    'weekday': weekday,
    'start_min': startMin,
    'end_min': endMin,
  };
}

class Appointment {
  const Appointment({required this.id, this.providerId, this.clientId, this.startsAt, this.durationMin, this.status, this.notes, this.createdAt});
  final String id;
  final String? providerId;
  final String? clientId;
  final String? startsAt;
  final int? durationMin;
  final String? status;
  final String? notes;
  final String? createdAt;

  factory Appointment.fromRow(Map<String, dynamic> r) => Appointment(
    id: (r['_pk'] ?? r['id']).toString(),
    providerId: r['provider_id']?.toString(),
    clientId: r['client_id']?.toString(),
    startsAt: r['starts_at']?.toString(),
    durationMin: r['duration_min'] is int ? r['duration_min'] : int.tryParse('${r['duration_min']}'),
    status: r['status']?.toString(),
    notes: r['notes']?.toString(),
    createdAt: r['created_at']?.toString(),
  );

  Map<String, dynamic> toPayload() => {
    'id': id,
    'provider_id': providerId,
    'client_id': clientId,
    'starts_at': startsAt,
    'duration_min': durationMin,
    'status': status,
    'notes': notes,
    'created_at': createdAt,
  };
}

class Invoice {
  const Invoice({required this.id, this.appointmentId, this.clientId, this.amountCents, this.status, this.issuedAt, this.createdAt, this.providerId, this.lineType, this.rateCents, this.hoursMin, this.description, this.dueAt, this.paidAt});
  final String id;
  final String? appointmentId;
  final String? clientId;
  final int? amountCents;
  final String? status;
  final String? issuedAt;
  final String? createdAt;
  final String? providerId;
  final String? lineType;
  final String? rateCents;
  final String? hoursMin;
  final String? description;
  final String? dueAt;
  final String? paidAt;

  factory Invoice.fromRow(Map<String, dynamic> r) => Invoice(
    id: (r['_pk'] ?? r['id']).toString(),
    appointmentId: r['appointment_id']?.toString(),
    clientId: r['client_id']?.toString(),
    amountCents: r['amount_cents'] is int ? r['amount_cents'] : int.tryParse('${r['amount_cents']}'),
    status: r['status']?.toString(),
    issuedAt: r['issued_at']?.toString(),
    createdAt: r['created_at']?.toString(),
    providerId: r['provider_id']?.toString(),
    lineType: r['line_type']?.toString(),
    rateCents: r['rate_cents']?.toString(),
    hoursMin: r['hours_min']?.toString(),
    description: r['description']?.toString(),
    dueAt: r['due_at']?.toString(),
    paidAt: r['paid_at']?.toString(),
  );

  Map<String, dynamic> toPayload() => {
    'id': id,
    'appointment_id': appointmentId,
    'client_id': clientId,
    'amount_cents': amountCents,
    'status': status,
    'issued_at': issuedAt,
    'created_at': createdAt,
    'provider_id': providerId,
    'line_type': lineType,
    'rate_cents': rateCents,
    'hours_min': hoursMin,
    'description': description,
    'due_at': dueAt,
    'paid_at': paidAt,
  };
}

class Message {
  const Message({required this.id, this.providerId, this.clientId, this.senderType, this.senderId, this.body, this.createdAt, this.readAt});
  final String id;
  final String? providerId;
  final String? clientId;
  final String? senderType;
  final String? senderId;
  final String? body;
  final String? createdAt;
  final String? readAt;

  factory Message.fromRow(Map<String, dynamic> r) => Message(
    id: (r['_pk'] ?? r['id']).toString(),
    providerId: r['provider_id']?.toString(),
    clientId: r['client_id']?.toString(),
    senderType: r['sender_type']?.toString(),
    senderId: r['sender_id']?.toString(),
    body: r['body']?.toString(),
    createdAt: r['created_at']?.toString(),
    readAt: r['read_at']?.toString(),
  );

  Map<String, dynamic> toPayload() => {
    'id': id,
    'provider_id': providerId,
    'client_id': clientId,
    'sender_type': senderType,
    'sender_id': senderId,
    'body': body,
    'created_at': createdAt,
    'read_at': readAt,
  };
}

