//! `nostos_rules.toml` load/save (ADR-0031).
//!
//! The on-disk file always carries both sync-mode sections — `[tables.*]`
//! (`toggles` mode, generator-owned) and `[[rules]]` (`hand` mode,
//! hand-authored) — so an operator can flip `sync_mode` without losing
//! whichever section isn't currently active. This module is the single
//! place that shape is serialized: a private serde mirror
//! ([`RulesFileMirror`]) maps the TOML tables to [`nostos_domain::SyncRules`],
//! keeping the domain type itself free of TOML-specific `serde` derives
//! (`nostos-domain` stays I/O-free — see `CLAUDE.md`).
//!
//! [`load`] validates before returning (`SyncRules::validate`), so a caller
//! never observes a structurally-invalid ruleset. A missing file is not an
//! error — it is the zero-config default, and the caller falls back to
//! `all` mode.

use std::collections::BTreeMap;
use std::path::Path;

use nostos_domain::{HandRule, RulesError, SyncMode, SyncRules, TableRule};
use serde::{Deserialize, Serialize};

/// Default file name, resolved relative to the process working directory.
pub const RULES_FILE_NAME: &str = "nostos_rules.toml";

const BANNER: &str = "# nostos_rules.toml — generated by `nostos rules init` (ADR-0031).\n\
# sync_mode selects WHICH section below is the truth:\n\
#   all     — sync everything; neither section is read (both are preserved)\n\
#   toggles — [tables.*] is the truth; `nostos rules edit` owns it\n\
#   hand    — [[rules]] is the truth; the generator is frozen\n\n";

#[derive(Debug, thiserror::Error)]
pub enum RulesFileError {
    #[error("reading {path}: {source}")]
    Io {
        path: String,
        source: std::io::Error,
    },
    #[error("malformed {path}: {source}")]
    Malformed {
        path: String,
        source: toml::de::Error,
    },
    #[error("invalid rules in {path}: {source}")]
    Invalid { path: String, source: RulesError },
    #[error("serializing rules: {0}")]
    Serialize(#[from] toml::ser::Error),
}

/// One `[tables.<name>]` entry — the generator-owned toggle-mode section.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct TableEntry {
    sync: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    scope: Option<String>,
}

/// One `[[rules]]` entry — the hand-authored section.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct RuleEntry {
    table: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    scope: Option<String>,
}

/// The serde-facing mirror of `nostos_rules.toml`. Kept private and separate
/// from [`SyncRules`] so the domain type never derives `serde` against a
/// TOML-specific shape (`BTreeMap<String, TableEntry>` for `[tables.*]`
/// exists only because that's how TOML spells a name-keyed section table;
/// the domain's `Vec<TableRule>` has no such format opinion).
#[derive(Debug, Clone, Serialize, Deserialize)]
struct RulesFileMirror {
    version: u32,
    sync_mode: String,
    #[serde(default)]
    tables: BTreeMap<String, TableEntry>,
    #[serde(default)]
    rules: Vec<RuleEntry>,
}

impl RulesFileMirror {
    fn from_domain(rules: &SyncRules) -> Self {
        let tables = rules
            .tables
            .iter()
            .map(|t| {
                (
                    t.table.clone(),
                    TableEntry {
                        sync: t.sync,
                        scope: t.scope.clone(),
                    },
                )
            })
            .collect();
        let rules_vec = rules
            .hand
            .iter()
            .map(|h| RuleEntry {
                table: h.table.clone(),
                scope: h.scope.clone(),
            })
            .collect();
        Self {
            version: rules.version,
            sync_mode: rules.mode.as_str().to_string(),
            tables,
            rules: rules_vec,
        }
    }

    /// Consumes the mirror into a domain `SyncRules`. Does NOT call
    /// `validate()` — callers that need the validated guarantee (`load`)
    /// call it themselves; `set_mode` deliberately skips it so it can
    /// round-trip a section that's inactive-but-currently-invalid without
    /// blocking the mode switch that would make it active-but-fixed later.
    fn into_domain(self, path: &Path) -> Result<SyncRules, RulesFileError> {
        let mode = SyncMode::parse(&self.sync_mode).ok_or_else(|| RulesFileError::Invalid {
            path: path.display().to_string(),
            source: RulesError::UnknownMode(self.sync_mode.clone()),
        })?;
        let tables = self
            .tables
            .into_iter()
            .map(|(table, entry)| TableRule {
                table,
                sync: entry.sync,
                scope: entry.scope,
            })
            .collect();
        let hand = self
            .rules
            .into_iter()
            .map(|r| HandRule {
                table: r.table,
                scope: r.scope,
            })
            .collect();
        Ok(SyncRules {
            version: self.version,
            mode,
            tables,
            hand,
        })
    }
}

fn io_err(path: &Path, source: std::io::Error) -> RulesFileError {
    RulesFileError::Io {
        path: path.display().to_string(),
        source,
    }
}

fn malformed_err(path: &Path, source: toml::de::Error) -> RulesFileError {
    RulesFileError::Malformed {
        path: path.display().to_string(),
        source,
    }
}

fn write_mirror(path: &Path, mirror: &RulesFileMirror) -> Result<(), RulesFileError> {
    let body = toml::to_string_pretty(mirror)?;
    std::fs::write(path, format!("{BANNER}{body}")).map_err(|e| io_err(path, e))
}

/// Read + validate. `Ok(None)` when the file does not exist (caller falls
/// back to `ActiveRuleset::all_mode()` — zero-config dev default).
pub fn load(path: &Path) -> Result<Option<SyncRules>, RulesFileError> {
    let text = match std::fs::read_to_string(path) {
        Ok(text) => text,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(e) => return Err(io_err(path, e)),
    };
    let mirror: RulesFileMirror = toml::from_str(&text).map_err(|e| malformed_err(path, e))?;
    let rules = mirror.into_domain(path)?;
    rules.validate().map_err(|source| RulesFileError::Invalid {
        path: path.display().to_string(),
        source,
    })?;
    Ok(Some(rules))
}

/// Write with the banner comment above. Overwrites; preserves BOTH sections
/// regardless of mode (truth-switching must never delete an artifact).
pub fn save(path: &Path, rules: &SyncRules) -> Result<(), RulesFileError> {
    write_mirror(path, &RulesFileMirror::from_domain(rules))
}

/// Rewrite ONLY `sync_mode`, leaving both sections byte-identical.
/// Used by `nostos rules edit --mode` and by mode-switch tests.
pub fn set_mode(path: &Path, mode: SyncMode) -> Result<(), RulesFileError> {
    let text = std::fs::read_to_string(path).map_err(|e| io_err(path, e))?;
    let mut mirror: RulesFileMirror = toml::from_str(&text).map_err(|e| malformed_err(path, e))?;
    mirror.sync_mode = mode.as_str().to_string();
    write_mirror(path, &mirror)
}

#[cfg(test)]
mod tests {
    use super::*;
    use nostos_domain::RULES_VERSION;

    /// A fresh, non-colliding path under `std::env::temp_dir()`. Each test
    /// gets its own directory so parallel test runs never race on the same
    /// file.
    fn temp_rules_path() -> std::path::PathBuf {
        let dir =
            std::env::temp_dir().join(format!("nostos-rules-file-test-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).expect("create temp dir");
        dir.join(RULES_FILE_NAME)
    }

    fn sample_rules(mode: SyncMode) -> SyncRules {
        SyncRules {
            version: RULES_VERSION,
            mode,
            tables: vec![
                TableRule {
                    table: "notes".to_string(),
                    sync: false,
                    scope: None,
                },
                TableRule {
                    table: "tasks".to_string(),
                    sync: true,
                    scope: Some("owner_id = claims.sub".to_string()),
                },
            ],
            hand: vec![HandRule {
                table: "tasks".to_string(),
                scope: Some("org_id = claims.org_id AND status != 'archived'".to_string()),
            }],
        }
    }

    #[test]
    fn round_trips_both_sections() {
        let path = temp_rules_path();
        let rules = sample_rules(SyncMode::Toggles);

        save(&path, &rules).expect("save");
        let loaded = load(&path).expect("load").expect("file exists");

        assert_eq!(loaded, rules);
        assert_eq!(loaded.tables.len(), 2);
        assert_eq!(loaded.hand.len(), 1);
    }

    #[test]
    fn missing_file_is_none() {
        let path = temp_rules_path();
        // temp_rules_path only creates the parent dir, not the file itself.
        assert_eq!(load(&path).expect("load"), None);
    }

    #[test]
    fn malformed_toml_is_malformed_error() {
        let path = temp_rules_path();
        std::fs::write(&path, "this is not [ valid toml").expect("write malformed");

        let err = load(&path).expect_err("malformed toml must error");
        match err {
            RulesFileError::Malformed { path: p, .. } => {
                assert_eq!(p, path.display().to_string());
            }
            other => panic!("expected Malformed, got {other:?}"),
        }
    }

    #[test]
    fn set_mode_preserves_sections() {
        let path = temp_rules_path();
        let rules = sample_rules(SyncMode::Toggles);
        save(&path, &rules).expect("save");

        set_mode(&path, SyncMode::Hand).expect("set_mode");

        let loaded = load(&path).expect("load").expect("file exists");
        assert_eq!(loaded.mode, SyncMode::Hand);
        // Both sections intact — only the active-mode interpretation moved.
        assert_eq!(loaded.tables, rules.tables);
        assert_eq!(loaded.hand, rules.hand);
    }

    #[test]
    fn load_rejects_future_version() {
        let path = temp_rules_path();
        let mut rules = sample_rules(SyncMode::All);
        rules.version = RULES_VERSION + 1;
        save(&path, &rules).expect("save");

        let err = load(&path).expect_err("future version must error");
        match err {
            RulesFileError::Invalid {
                source: RulesError::UnsupportedVersion(v),
                ..
            } => assert_eq!(v, RULES_VERSION + 1),
            other => panic!("expected Invalid/UnsupportedVersion, got {other:?}"),
        }
    }
}
