//! `nostos_rules.toml` load/save (ADR-0031).
//!
//! The on-disk file always carries both sync-mode sections — `[tables.*]`
//! (`toggles` mode, generator-owned) and `[[rules]]` (`hand` mode,
//! hand-authored) — so an operator can flip `sync_mode` without losing
//! whichever section isn't currently active. This module is the single
//! place that shape is serialized: a private serde mirror
//! ([`RulesFileMirror`]) maps the TOML tables to [`nostos_domain::SyncRules`],
//! keeping the domain type itself free of TOML-specific `serde` derives
//! (`nostos-domain` stays I/O-free — see `CLAUDE.md`).
//!
//! [`load`] validates before returning (`SyncRules::validate`), so a caller
//! never observes a structurally-invalid ruleset. A missing file is not an
//! error — it is the zero-config default, and the caller falls back to
//! `all` mode.

use std::collections::BTreeMap;
use std::path::Path;

use nostos_domain::{HandRule, RulesError, SyncMode, SyncRules, TableRule};
use serde::{Deserialize, Serialize};

/// Default file name, resolved relative to the process working directory.
pub const RULES_FILE_NAME: &str = "nostos_rules.toml";

const BANNER: &str = "# nostos_rules.toml — generated by `nostos rules init` (ADR-0031).\n\
# sync_mode selects WHICH section below is the truth:\n\
#   all     — sync everything; neither section is read (both are preserved)\n\
#   toggles — [tables.*] is the truth; `nostos rules edit` owns it\n\
#   hand    — [[rules]] is the truth; the generator is frozen\n\n";

#[derive(Debug, thiserror::Error)]
pub enum RulesFileError {
    #[error("reading {path}: {source}")]
    Io {
        path: String,
        source: std::io::Error,
    },
    #[error("malformed {path}: {source}")]
    Malformed {
        path: String,
        source: toml::de::Error,
    },
    #[error("invalid rules in {path}: {source}")]
    Invalid { path: String, source: RulesError },
    #[error("serializing rules: {0}")]
    Serialize(#[from] toml::ser::Error),
}

/// One `[tables.<name>]` entry — the generator-owned toggle-mode section.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct TableEntry {
    sync: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    scope: Option<String>,
}

/// One `[[rules]]` entry — the hand-authored section.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct RuleEntry {
    table: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    scope: Option<String>,
}

/// One `[streams.<name>]` entry — the P5 sync-streams section
/// (docs/plans/p5-sync-streams-design.md Decision 1). `where` is the
/// predicate template with `:param` placeholders; it is a Rust keyword, so
/// the field is `template` here and renamed only at the serde boundary.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct StreamEntry {
    table: String,
    #[serde(rename = "where")]
    template: String,
}

/// The serde-facing mirror of `nostos_rules.toml`. Kept private and separate
/// from [`SyncRules`] so the domain type never derives `serde` against a
/// TOML-specific shape (`BTreeMap<String, TableEntry>` for `[tables.*]`
/// exists only because that's how TOML spells a name-keyed section table;
/// the domain's `Vec<TableRule>` has no such format opinion).
#[derive(Debug, Clone, Serialize, Deserialize)]
struct RulesFileMirror {
    version: u32,
    sync_mode: String,
    #[serde(default)]
    tables: BTreeMap<String, TableEntry>,
    #[serde(default)]
    rules: Vec<RuleEntry>,
    /// `[streams.<name>]` — name-keyed like `[tables.*]` (P5). Absent in
    /// pre-P5 files → empty (serde default); unknown to old binaries, which
    /// ignore it (no `deny_unknown_fields`).
    #[serde(default)]
    streams: BTreeMap<String, StreamEntry>,
}

impl RulesFileMirror {
    fn from_domain(rules: &SyncRules) -> Self {
        let tables = rules
            .tables
            .iter()
            .map(|t| {
                (
                    t.table.clone(),
                    TableEntry {
                        sync: t.sync,
                        scope: t.scope.clone(),
                    },
                )
            })
            .collect();
        let rules_vec = rules
            .hand
            .iter()
            .map(|h| RuleEntry {
                table: h.table.clone(),
                scope: h.scope.clone(),
            })
            .collect();
        let streams = rules
            .streams
            .iter()
            .map(|s| {
                (
                    s.name.clone(),
                    StreamEntry {
                        table: s.table.clone(),
                        template: s.template.clone(),
                    },
                )
            })
            .collect();
        Self {
            version: rules.version,
            sync_mode: rules.mode.as_str().to_string(),
            tables,
            rules: rules_vec,
            streams,
        }
    }

    /// Consumes the mirror into a domain `SyncRules`. Does NOT call
    /// `validate()` — callers that need the validated guarantee (`load`)
    /// call it themselves; `set_mode` deliberately skips it so it can
    /// round-trip a section that's inactive-but-currently-invalid without
    /// blocking the mode switch that would make it active-but-fixed later.
    fn into_domain(self, path: &Path) -> Result<SyncRules, RulesFileError> {
        let mode = SyncMode::parse(&self.sync_mode).ok_or_else(|| RulesFileError::Invalid {
            path: path.display().to_string(),
            source: RulesError::UnknownMode(self.sync_mode.clone()),
        })?;
        let tables = self
            .tables
            .into_iter()
            .map(|(table, entry)| TableRule {
                table,
                sync: entry.sync,
                scope: entry.scope,
            })
            .collect();
        let hand = self
            .rules
            .into_iter()
            .map(|r| HandRule {
                table: r.table,
                scope: r.scope,
            })
            .collect();
        let streams = self
            .streams
            .into_iter()
            .map(|(name, entry)| nostos_domain::StreamRule {
                name,
                table: entry.table,
                template: entry.template,
            })
            .collect();
        Ok(SyncRules {
            version: self.version,
            mode,
            tables,
            hand,
            streams,
        })
    }
}

fn io_err(path: &Path, source: std::io::Error) -> RulesFileError {
    RulesFileError::Io {
        path: path.display().to_string(),
        source,
    }
}

fn malformed_err(path: &Path, source: toml::de::Error) -> RulesFileError {
    RulesFileError::Malformed {
        path: path.display().to_string(),
        source,
    }
}

/// Atomic write (Task 20, `PUT /rules`): write the full contents to a temp
/// file in the SAME directory as `path`, `fsync` it, then `rename` over
/// `path`. Same-directory is required — a temp file under `/tmp` risks a
/// cross-filesystem `rename`, which fails outright instead of being atomic.
/// A reader (or the Task 14 poll watcher) never observes a partially-written
/// file: `rename` is atomic on POSIX, so `path` is either the old contents or
/// the new ones, never a mix.
/// Disambiguates concurrent `write_mirror` calls in the same process that
/// land on the same tmp-file name within the same PID (e.g. two rapid `PUT
/// /rules` requests) — see [`write_mirror`].
static TMP_FILE_COUNTER: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);

fn write_mirror(path: &Path, mirror: &RulesFileMirror) -> Result<(), RulesFileError> {
    use std::io::Write as _;
    use std::sync::atomic::Ordering;

    let body = toml::to_string_pretty(mirror)?;
    let contents = format!("{BANNER}{body}");

    let dir = path
        .parent()
        .filter(|p| !p.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    let file_name = path.file_name().map_or_else(
        || "nostos_rules.toml".to_string(),
        |n| n.to_string_lossy().into_owned(),
    );
    let n = TMP_FILE_COUNTER.fetch_add(1, Ordering::Relaxed);
    let tmp_path = dir.join(format!(".{file_name}.tmp.{}.{n}", std::process::id()));

    let write_result = (|| -> std::io::Result<()> {
        let mut file = std::fs::File::create(&tmp_path)?;
        file.write_all(contents.as_bytes())?;
        file.sync_all()
    })();
    let Err(e) = write_result else {
        return std::fs::rename(&tmp_path, path).map_err(|e| {
            let _ = std::fs::remove_file(&tmp_path);
            io_err(path, e)
        });
    };
    let _ = std::fs::remove_file(&tmp_path);
    Err(io_err(path, e))
}

/// Read + validate. `Ok(None)` when the file does not exist (caller falls
/// back to `ActiveRuleset::all_mode()` — zero-config dev default).
pub fn load(path: &Path) -> Result<Option<SyncRules>, RulesFileError> {
    let text = match std::fs::read_to_string(path) {
        Ok(text) => text,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(e) => return Err(io_err(path, e)),
    };
    let mirror: RulesFileMirror = toml::from_str(&text).map_err(|e| malformed_err(path, e))?;
    let rules = mirror.into_domain(path)?;
    rules.validate().map_err(|source| RulesFileError::Invalid {
        path: path.display().to_string(),
        source,
    })?;
    Ok(Some(rules))
}

/// Write with the banner comment above. Overwrites; preserves BOTH sections
/// regardless of mode (truth-switching must never delete an artifact).
pub fn save(path: &Path, rules: &SyncRules) -> Result<(), RulesFileError> {
    write_mirror(path, &RulesFileMirror::from_domain(rules))
}

/// Rewrite ONLY `sync_mode`, leaving both sections byte-identical.
/// Used by `nostos rules edit --mode` and by mode-switch tests.
pub fn set_mode(path: &Path, mode: SyncMode) -> Result<(), RulesFileError> {
    let text = std::fs::read_to_string(path).map_err(|e| io_err(path, e))?;
    let mut mirror: RulesFileMirror = toml::from_str(&text).map_err(|e| malformed_err(path, e))?;
    mirror.sync_mode = mode.as_str().to_string();
    write_mirror(path, &mirror)
}

#[cfg(test)]
mod tests {
    use super::*;
    use nostos_domain::RULES_VERSION;

    /// A fresh, non-colliding path under `std::env::temp_dir()`. Each test
    /// gets its own directory so parallel test runs never race on the same
    /// file.
    fn temp_rules_path() -> std::path::PathBuf {
        let dir =
            std::env::temp_dir().join(format!("nostos-rules-file-test-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).expect("create temp dir");
        dir.join(RULES_FILE_NAME)
    }

    fn sample_rules(mode: SyncMode) -> SyncRules {
        SyncRules {
            version: RULES_VERSION,
            mode,
            tables: vec![
                TableRule {
                    table: "notes".to_string(),
                    sync: false,
                    scope: None,
                },
                TableRule {
                    table: "tasks".to_string(),
                    sync: true,
                    scope: Some("owner_id = claims.sub".to_string()),
                },
            ],
            hand: vec![HandRule {
                table: "tasks".to_string(),
                scope: Some("org_id = claims.org_id AND status != 'archived'".to_string()),
            }],
            streams: Vec::new(),
        }
    }

    #[test]
    fn round_trips_both_sections() {
        let path = temp_rules_path();
        let rules = sample_rules(SyncMode::Toggles);

        save(&path, &rules).expect("save");
        let loaded = load(&path).expect("load").expect("file exists");

        assert_eq!(loaded, rules);
        assert_eq!(loaded.tables.len(), 2);
        assert_eq!(loaded.hand.len(), 1);
    }

    #[test]
    fn missing_file_is_none() {
        let path = temp_rules_path();
        // temp_rules_path only creates the parent dir, not the file itself.
        assert_eq!(load(&path).expect("load"), None);
    }

    #[test]
    fn malformed_toml_is_malformed_error() {
        let path = temp_rules_path();
        std::fs::write(&path, "this is not [ valid toml").expect("write malformed");

        let err = load(&path).expect_err("malformed toml must error");
        match err {
            RulesFileError::Malformed { path: p, .. } => {
                assert_eq!(p, path.display().to_string());
            }
            other => panic!("expected Malformed, got {other:?}"),
        }
    }

    #[test]
    fn set_mode_preserves_sections() {
        let path = temp_rules_path();
        let rules = sample_rules(SyncMode::Toggles);
        save(&path, &rules).expect("save");

        set_mode(&path, SyncMode::Hand).expect("set_mode");

        let loaded = load(&path).expect("load").expect("file exists");
        assert_eq!(loaded.mode, SyncMode::Hand);
        // Both sections intact — only the active-mode interpretation moved.
        assert_eq!(loaded.tables, rules.tables);
        assert_eq!(loaded.hand, rules.hand);
    }

    #[test]
    fn load_rejects_future_version() {
        let path = temp_rules_path();
        let mut rules = sample_rules(SyncMode::All);
        rules.version = RULES_VERSION + 1;
        save(&path, &rules).expect("save");

        let err = load(&path).expect_err("future version must error");
        match err {
            RulesFileError::Invalid {
                source: RulesError::UnsupportedVersion(v),
                ..
            } => assert_eq!(v, RULES_VERSION + 1),
            other => panic!("expected Invalid/UnsupportedVersion, got {other:?}"),
        }
    }

    // ---- P5 sync streams: the `[streams]` section ----

    #[test]
    fn streams_round_trip_through_the_file() {
        let path = temp_rules_path();
        let mut rules = sample_rules(SyncMode::Toggles);
        rules.streams = vec![
            nostos_domain::StreamRule {
                name: "lists".to_string(),
                table: "lists".to_string(),
                template: "owner_id = :owner AND priority >= :min".to_string(),
            },
            nostos_domain::StreamRule {
                name: "inbox".to_string(),
                table: "messages".to_string(),
                template: "folder = :folder".to_string(),
            },
        ];
        save(&path, &rules).expect("save");

        // The TOML shape is the documented `[streams.<name>]` with a `where` key.
        let text = std::fs::read_to_string(&path).expect("read back");
        assert!(text.contains("[streams.lists]"), "got:\n{text}");
        assert!(
            text.contains("where = 'owner_id = :owner AND priority >= :min'")
                || text.contains("where = \"owner_id = :owner AND priority >= :min\""),
            "got:\n{text}"
        );

        let loaded = load(&path).expect("load").expect("file exists");
        // Streams are name-keyed in the file (`[streams.<name>]`), so the
        // round-trip is order-normalizing: compare as sorted sets.
        let mut loaded_streams = loaded.streams.clone();
        loaded_streams.sort_by(|a, b| a.name.cmp(&b.name));
        let mut expected_streams = rules.streams.clone();
        expected_streams.sort_by(|a, b| a.name.cmp(&b.name));
        assert_eq!(loaded_streams, expected_streams);
        assert_eq!(loaded.tables, rules.tables);
        assert_eq!(loaded.hand, rules.hand);
        assert_eq!(loaded_streams.len(), 2);
    }

    #[test]
    fn pre_p5_file_without_streams_loads_empty() {
        let path = temp_rules_path();
        std::fs::write(&path, "version = 1\nsync_mode = \"all\"\n").expect("write minimal file");
        let loaded = load(&path).expect("load").expect("file exists");
        assert!(loaded.streams.is_empty());
    }

    #[test]
    fn bad_stream_template_is_a_loud_boot_error_in_any_mode() {
        // Even under `all` (where table sections are inert), a malformed
        // stream template fails validation at load (design §2).
        let path = temp_rules_path();
        let mut rules = sample_rules(SyncMode::All);
        rules.streams = vec![nostos_domain::StreamRule {
            name: "evil".to_string(),
            table: "tasks".to_string(),
            template: "owner = :owner; DROP TABLE tasks;--".to_string(),
        }];
        save(&path, &rules).expect("save");

        let err = load(&path).expect_err("injection-shaped template must error");
        match err {
            RulesFileError::Invalid {
                source: RulesError::StreamTemplate { name, .. },
                ..
            } => assert_eq!(name, "evil"),
            other => panic!("expected Invalid/StreamTemplate, got {other:?}"),
        }
    }

    #[test]
    fn duplicate_stream_name_is_rejected() {
        // `[streams.<name>]` is name-keyed, so a file cannot express a
        // duplicate (TOML rejects a repeated table as malformed). The check
        // guards in-memory constructions (e.g. a future management endpoint);
        // exercise it at the domain layer directly.
        let rules = SyncRules {
            version: RULES_VERSION,
            mode: SyncMode::All,
            tables: Vec::new(),
            hand: Vec::new(),
            streams: vec![
                nostos_domain::StreamRule {
                    name: "lists".to_string(),
                    table: "lists".to_string(),
                    template: "owner = :o".to_string(),
                },
                nostos_domain::StreamRule {
                    name: "lists".to_string(),
                    table: "other".to_string(),
                    template: "owner = :o".to_string(),
                },
            ],
        };
        let err = rules
            .validate()
            .expect_err("duplicate stream name must error");
        match err {
            RulesError::DuplicateStream(name) => assert_eq!(name, "lists"),
            other => panic!("expected DuplicateStream, got {other:?}"),
        }
    }

    #[test]
    fn streams_edit_changes_the_checksum_under_every_mode() {
        // Design checklist: a streams edit = a rules edit → resnapshot. Under
        // `all` the table sections are inert, but streams must still move the
        // checksum.
        for mode in [SyncMode::All, SyncMode::Toggles, SyncMode::Hand] {
            let base = sample_rules(mode);
            let mut with_stream = base.clone();
            with_stream.streams = vec![nostos_domain::StreamRule {
                name: "lists".to_string(),
                table: "lists".to_string(),
                template: "owner = :owner".to_string(),
            }];
            assert_ne!(
                base.checksum(),
                with_stream.checksum(),
                "mode {mode:?}: adding a stream must change the checksum"
            );
        }
    }

    #[test]
    fn stream_template_whitespace_noise_does_not_change_checksum() {
        let mut a = sample_rules(SyncMode::All);
        a.streams = vec![nostos_domain::StreamRule {
            name: "lists".to_string(),
            table: "lists".to_string(),
            template: "owner = :owner AND priority >= :min".to_string(),
        }];
        let mut b = sample_rules(SyncMode::All);
        b.streams = vec![nostos_domain::StreamRule {
            name: "lists".to_string(),
            table: "lists".to_string(),
            template: "  owner=:owner   AND\n priority  >=  :min ".to_string(),
        }];
        assert_eq!(a.checksum(), b.checksum());
    }

    #[test]
    fn set_mode_preserves_streams() {
        let path = temp_rules_path();
        let mut rules = sample_rules(SyncMode::Toggles);
        rules.streams = vec![nostos_domain::StreamRule {
            name: "lists".to_string(),
            table: "lists".to_string(),
            template: "owner = :owner".to_string(),
        }];
        save(&path, &rules).expect("save");

        set_mode(&path, SyncMode::Hand).expect("set_mode");

        let loaded = load(&path).expect("load").expect("file exists");
        assert_eq!(loaded.mode, SyncMode::Hand);
        assert_eq!(loaded.streams, rules.streams);
    }
}
