//! `nostos.toml` — the project config `nostos init` writes and every other
//! subcommand reads. Deliberately holds NO secrets: the Postgres URL and any
//! JWT secret live in `.env` (gitignored), and this file stores only an
//! env-var *name* reference (`db.url_env`) plus non-secret sync topology so
//! it is safe to commit alongside the app.

use std::path::Path;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

pub const DEFAULT_FILE_NAME: &str = "nostos.toml";

fn default_tenant_column() -> String {
    "org_id".to_string()
}

fn default_url_env() -> String {
    "NOSTOS_PG_URL".to_string()
}

fn default_publication() -> String {
    "cairn_pub".to_string()
}

fn default_slot() -> String {
    "cairn_slot".to_string()
}

fn default_bind() -> String {
    "0.0.0.0:8800".to_string()
}

fn default_ws_path() -> String {
    "/sync".to_string()
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SyncSection {
    /// Tables to sync. Also the scope of the Postgres publication `nostos
    /// init` creates/updates.
    pub tables: Vec<String>,
    /// Write-back allowlist (ADR-0013) — must be a subset of `tables`.
    /// Empty = read-only sync (matches the server's own "empty = no tables
    /// writable" default).
    #[serde(default)]
    pub write_tables: Vec<String>,
    /// The tenant column enforced on every predicate (ADR-0011) once auth is
    /// `supabase-jwt`. Matches the server's own default.
    #[serde(default = "default_tenant_column")]
    pub tenant_column: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DbSection {
    /// The NAME of the env var (in `.env`, not here) that holds the direct
    /// Postgres connection string. Never the URL itself — see module docs.
    #[serde(default = "default_url_env")]
    pub url_env: String,
    #[serde(default = "default_publication")]
    pub publication: String,
    #[serde(default = "default_slot")]
    pub slot: String,
}

impl Default for DbSection {
    fn default() -> Self {
        Self {
            url_env: default_url_env(),
            publication: default_publication(),
            slot: default_slot(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SupabaseSection {
    pub url: String,
    /// Derived as `<url>/auth/v1/.well-known/jwks.json`. Stored (not
    /// recomputed each time) so `doctor` and the future JWKS auth wiring
    /// (W2 — RS256/ES256, not landed yet) have one source of truth. NOTE:
    /// `nostos dev` does not map this to any `NOSTOS_*` env var today — the
    /// server only understands HS256 (`NOSTOS_SUPABASE_JWT_SECRET`).
    pub jwks_url: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ServerSection {
    #[serde(default = "default_bind")]
    pub bind: String,
    #[serde(default = "default_ws_path")]
    pub ws_path: String,
}

impl Default for ServerSection {
    fn default() -> Self {
        Self {
            bind: default_bind(),
            ws_path: default_ws_path(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NostosConfig {
    pub sync: SyncSection,
    #[serde(default)]
    pub db: DbSection,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub supabase: Option<SupabaseSection>,
    #[serde(default)]
    pub server: ServerSection,
}

impl NostosConfig {
    /// Load `nostos.toml` from `path`. Returns a clear error (not a panic) if
    /// missing or malformed — every subcommand but `init` requires this file.
    pub fn load(path: &Path) -> Result<Self> {
        let text = std::fs::read_to_string(path).with_context(|| {
            format!(
                "no {} found at {} — run `nostos init` first",
                DEFAULT_FILE_NAME,
                path.display()
            )
        })?;
        toml::from_str(&text).with_context(|| format!("malformed {}", path.display()))
    }

    /// Serialize and write `nostos.toml`. Overwrites any existing file —
    /// re-running `nostos init` is expected to update the config in place.
    pub fn save(&self, path: &Path) -> Result<()> {
        let text = toml::to_string_pretty(self).context("serializing nostos.toml")?;
        let banner = "# nostos.toml — generated by `nostos init`. Safe to commit: no secrets live\n\
                       # here. The Postgres URL lives in .env (gitignored); see db.url_env.\n\n";
        std::fs::write(path, format!("{banner}{text}"))
            .with_context(|| format!("writing {}", path.display()))
    }

    /// The `NOSTOS_*` environment variables `nostos dev` passes to the
    /// `nostos-server` child process. Deliberately narrow: only vars
    /// `crates/nostos-server/src/main.rs` actually parses today. `pg_url` and
    /// `jwt_secret` come from `.env`, not this struct.
    #[must_use]
    pub fn server_env(&self, pg_url: &str, jwt_secret: Option<&str>) -> Vec<(String, String)> {
        let mut env = vec![
            ("NOSTOS_BIND".to_string(), self.server.bind.clone()),
            ("NOSTOS_WS_PATH".to_string(), self.server.ws_path.clone()),
            ("NOSTOS_REPLICATOR".to_string(), "pg".to_string()),
            ("NOSTOS_PG_URL".to_string(), pg_url.to_string()),
            ("NOSTOS_PG_SLOT".to_string(), self.db.slot.clone()),
            (
                "NOSTOS_PG_PUBLICATION".to_string(),
                self.db.publication.clone(),
            ),
            (
                "NOSTOS_WRITE_TABLES".to_string(),
                self.sync.write_tables.join(","),
            ),
        ];
        // The server only supports HS256 (NOSTOS_SUPABASE_JWT_SECRET) today —
        // RS256/ES256 JWKS verification is W2 (pending). Only flip on
        // supabase-jwt auth when a secret is actually present in .env;
        // otherwise stay `none` (anonymous, single-tenant dev default) rather
        // than emit a NOSTOS_SYNC_AUTH the server would reject/misconfigure.
        if let Some(secret) = jwt_secret.filter(|s| !s.is_empty()) {
            env.push(("NOSTOS_SYNC_AUTH".to_string(), "supabase-jwt".to_string()));
            env.push(("NOSTOS_SUPABASE_JWT_SECRET".to_string(), secret.to_string()));
            env.push((
                "NOSTOS_TENANT_COLUMN".to_string(),
                self.sync.tenant_column.clone(),
            ));
        }
        env
    }
}

// ============================================================================
// `.nostos/` — app-side project config (ADR-0023). Distinct from `NostosConfig`
// (`nostos.toml`) above, which is the operator-side server-run config.
// ============================================================================

/// `.nostos/` directory name (tool-owned; sits at the app repo root).
pub const DOT_NOSTOS_DIR: &str = ".nostos";
/// `.nostos/config.json` — committed app-side config (`nostos link` writes it).
pub const CONFIG_JSON: &str = "config.json";
/// `.nostos/schema.json` — committed SchemaDescriptor mirror (ADR-0021 shape).
pub const SCHEMA_JSON: &str = "schema.json";
/// `.nostos/local/` — gitignored secrets + tool state.
pub const LOCAL_DIR: &str = "local";

/// The backend an app syncs against (ADR-0023 D4). Supabase is a preset over
/// the `postgres` adapter, not a fork; `appwrite` is post-v1.
///
/// Only PUBLISHABLE credentials belong here (the Supabase anon key is safe to
/// ship in a client bundle). Service-role keys, JWT secrets, and DB passwords
/// live in `.env` or `.nostos/local/` (gitignored) — never in this file.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "lowercase")]
pub enum Backend {
    /// Plain Postgres — logical replication, bring-your-own / no auth.
    Postgres,
    /// Supabase (v1) — Postgres + Supabase JWKS auth + anon-key client.
    Supabase {
        /// Project URL, e.g. `https://xyz.supabase.co`.
        url: String,
        /// Publishable (anon) key — safe to commit and ship in the client.
        anon_key: String,
    },
    /// Appwrite (post-v1) — realtime/events change source + REST write-back.
    Appwrite {
        endpoint: String,
        project_id: String,
    },
}

/// `.nostos/config.json` — the app-side project config `nostos link` writes and
/// `nostos gen` / `nostos pull` read.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProjectConfig {
    /// Human project name (informational).
    pub project: String,
    /// The nostos-server `/sync` WebSocket URL (`ws://` or `wss://`).
    pub sync_url: String,
    /// Backend preset (ADR-0023 D4). `None` = plain Postgres.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backend: Option<Backend>,
}

impl ProjectConfig {
    /// Load `.nostos/config.json` from `dir`.
    ///
    /// # Errors
    /// [`anyhow::Error`] if the file is missing or malformed.
    pub fn load(dir: &Path) -> Result<Self> {
        let path = dir.join(DOT_NOSTOS_DIR).join(CONFIG_JSON);
        let text = std::fs::read_to_string(&path).with_context(|| {
            format!(
                "no {}/{} found at {} — run `nostos link` first",
                DOT_NOSTOS_DIR,
                CONFIG_JSON,
                path.display()
            )
        })?;
        serde_json::from_str(&text).with_context(|| format!("malformed {}", path.display()))
    }

    /// Write `.nostos/config.json` into `dir` (pretty JSON; creates `.nostos/`
    /// if absent). Pure JSON — no banner comment, because strict JSON (what
    /// [`serde_json::from_str`] parses on [`Self::load`]) forbids `//`.
    /// The "safe to commit / publishable keys only" note is printed by
    /// `nostos link` at runtime instead.
    ///
    /// # Errors
    /// [`anyhow::Error`] on serialize or IO failure.
    pub fn save(&self, dir: &Path) -> Result<()> {
        let nostos_dir = dir.join(DOT_NOSTOS_DIR);
        std::fs::create_dir_all(&nostos_dir)
            .with_context(|| format!("creating {}", nostos_dir.display()))?;
        let path = nostos_dir.join(CONFIG_JSON);
        let text = serde_json::to_string_pretty(self).context("serializing config.json")?;
        std::fs::write(&path, format!("{text}\n"))
            .with_context(|| format!("writing {}", path.display()))
    }

    /// Derive the HTTP base for `GET /schema` from `sync_url`: `wss`→`https`,
    /// `ws`→`http`, host+port preserved, path stripped.
    #[must_use]
    pub fn http_base(&self) -> String {
        let translated = if let Some(rest) = self.sync_url.strip_prefix("wss://") {
            format!("https://{rest}")
        } else if let Some(rest) = self.sync_url.strip_prefix("ws://") {
            format!("http://{rest}")
        } else {
            self.sync_url.clone()
        };
        let authority_start = translated.find("://").map_or(0, |i| i + 3);
        let path_start = translated[authority_start..]
            .find('/')
            .map_or(translated.len(), |i| authority_start + i);
        translated[..path_start].to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> NostosConfig {
        NostosConfig {
            sync: SyncSection {
                tables: vec!["tasks".into(), "notes".into()],
                write_tables: vec!["tasks".into()],
                tenant_column: "org_id".into(),
            },
            db: DbSection::default(),
            supabase: Some(SupabaseSection {
                url: "https://xyz.supabase.co".into(),
                jwks_url: "https://xyz.supabase.co/auth/v1/.well-known/jwks.json".into(),
            }),
            server: ServerSection::default(),
        }
    }

    #[test]
    fn round_trips_through_toml() {
        let cfg = sample();
        let text = toml::to_string_pretty(&cfg).unwrap();
        let back: NostosConfig = toml::from_str(&text).unwrap();
        assert_eq!(cfg, back);
    }

    #[test]
    fn save_then_load_round_trips_via_disk() {
        let dir = std::env::temp_dir().join(format!("nostos-cli-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join(DEFAULT_FILE_NAME);
        let cfg = sample();
        cfg.save(&path).unwrap();
        let loaded = NostosConfig::load(&path).unwrap();
        assert_eq!(cfg, loaded);
        // Never write secrets into nostos.toml — url_env is a name, not a URL.
        let text = std::fs::read_to_string(&path).unwrap();
        assert!(!text.contains("postgres://"));
        assert!(!text.contains("postgresql://"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn minimal_toml_fills_defaults() {
        let text = "[sync]\ntables = [\"tasks\"]\n";
        let cfg: NostosConfig = toml::from_str(text).unwrap();
        assert_eq!(cfg.sync.tenant_column, "org_id");
        assert_eq!(cfg.db.publication, "cairn_pub");
        assert_eq!(cfg.db.slot, "cairn_slot");
        assert_eq!(cfg.server.bind, "0.0.0.0:8800");
        assert!(cfg.supabase.is_none());
    }

    #[test]
    fn server_env_omits_auth_vars_without_a_secret() {
        let cfg = sample();
        let env = cfg.server_env("postgresql://u:p@h/db", None);
        assert!(env
            .iter()
            .any(|(k, v)| k == "NOSTOS_PG_URL" && v.contains("postgresql://")));
        assert!(env
            .iter()
            .any(|(k, v)| k == "NOSTOS_REPLICATOR" && v == "pg"));
        assert!(env
            .iter()
            .any(|(k, v)| k == "NOSTOS_WRITE_TABLES" && v == "tasks"));
        assert!(!env.iter().any(|(k, _)| k == "NOSTOS_SYNC_AUTH"));
        assert!(!env.iter().any(|(k, _)| k == "NOSTOS_SUPABASE_JWT_SECRET"));
    }

    #[test]
    fn server_env_includes_auth_vars_with_a_secret() {
        let cfg = sample();
        let env = cfg.server_env("postgresql://u:p@h/db", Some("shh"));
        assert!(env
            .iter()
            .any(|(k, v)| k == "NOSTOS_SYNC_AUTH" && v == "supabase-jwt"));
        assert!(env
            .iter()
            .any(|(k, v)| k == "NOSTOS_SUPABASE_JWT_SECRET" && v == "shh"));
        assert!(env
            .iter()
            .any(|(k, v)| k == "NOSTOS_TENANT_COLUMN" && v == "org_id"));
    }
}

#[cfg(test)]
mod project_config_tests {
    use super::*;

    fn supabase_cfg() -> ProjectConfig {
        ProjectConfig {
            project: "demo".into(),
            sync_url: "wss://nostos.example.com/sync".into(),
            backend: Some(Backend::Supabase {
                url: "https://xyz.supabase.co".into(),
                anon_key: "ey.publishable".into(),
            }),
        }
    }

    #[test]
    fn round_trips_through_json() {
        let cfg = supabase_cfg();
        let text = serde_json::to_string(&cfg).unwrap();
        let back: ProjectConfig = serde_json::from_str(&text).unwrap();
        assert_eq!(cfg, back);
    }

    #[test]
    fn postgres_backend_is_unit_tag() {
        let json = serde_json::to_string(&Backend::Postgres).unwrap();
        assert_eq!(json, r#"{"kind":"postgres"}"#);
    }

    #[test]
    fn http_base_translates_scheme_and_strips_path() {
        assert_eq!(supabase_cfg().http_base(), "https://nostos.example.com");
        let pg = ProjectConfig {
            project: "p".into(),
            sync_url: "ws://127.0.0.1:8800/sync".into(),
            backend: None,
        };
        assert_eq!(pg.http_base(), "http://127.0.0.1:8800");
    }

    #[test]
    fn save_then_load_round_trips_via_disk() {
        let dir = std::env::temp_dir().join(format!("nostos-dotnostos-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let cfg = supabase_cfg();
        cfg.save(&dir).unwrap();
        let loaded = ProjectConfig::load(&dir).unwrap();
        assert_eq!(cfg, loaded);
        std::fs::remove_dir_all(&dir).ok();
    }
}
