//! `nostos.toml` — the project config `nostos init` writes and every other
//! subcommand reads. Deliberately holds NO secrets: the Postgres URL and any
//! JWT secret live in `.env` (gitignored), and this file stores only an
//! env-var *name* reference (`db.url_env`) plus non-secret sync topology so
//! it is safe to commit alongside the app.

use std::path::Path;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

pub const DEFAULT_FILE_NAME: &str = "nostos.toml";

fn default_tenant_column() -> String {
    "org_id".to_string()
}

fn default_url_env() -> String {
    "NOSTOS_PG_URL".to_string()
}

fn default_publication() -> String {
    "cairn_pub".to_string()
}

fn default_slot() -> String {
    "cairn_slot".to_string()
}

fn default_bind() -> String {
    "0.0.0.0:8800".to_string()
}

fn default_ws_path() -> String {
    "/sync".to_string()
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SyncSection {
    /// Tables to sync. Also the scope of the Postgres publication `nostos
    /// init` creates/updates.
    pub tables: Vec<String>,
    /// Write-back allowlist (ADR-0013) — must be a subset of `tables`.
    /// Empty = read-only sync (matches the server's own "empty = no tables
    /// writable" default).
    #[serde(default)]
    pub write_tables: Vec<String>,
    /// The tenant column enforced on every predicate (ADR-0011) once auth is
    /// `supabase-jwt`. Matches the server's own default.
    #[serde(default = "default_tenant_column")]
    pub tenant_column: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DbSection {
    /// The NAME of the env var (in `.env`, not here) that holds the direct
    /// Postgres connection string. Never the URL itself — see module docs.
    #[serde(default = "default_url_env")]
    pub url_env: String,
    #[serde(default = "default_publication")]
    pub publication: String,
    #[serde(default = "default_slot")]
    pub slot: String,
}

impl Default for DbSection {
    fn default() -> Self {
        Self {
            url_env: default_url_env(),
            publication: default_publication(),
            slot: default_slot(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SupabaseSection {
    pub url: String,
    /// Derived as `<url>/auth/v1/.well-known/jwks.json`. Stored (not
    /// recomputed each time) so `doctor` and the future JWKS auth wiring
    /// (W2 — RS256/ES256, not landed yet) have one source of truth. NOTE:
    /// `nostos dev` does not map this to any `NOSTOS_*` env var today — the
    /// server only understands HS256 (`NOSTOS_SUPABASE_JWT_SECRET`).
    pub jwks_url: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ServerSection {
    #[serde(default = "default_bind")]
    pub bind: String,
    #[serde(default = "default_ws_path")]
    pub ws_path: String,
}

impl Default for ServerSection {
    fn default() -> Self {
        Self {
            bind: default_bind(),
            ws_path: default_ws_path(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NostosConfig {
    pub sync: SyncSection,
    #[serde(default)]
    pub db: DbSection,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub supabase: Option<SupabaseSection>,
    #[serde(default)]
    pub server: ServerSection,
}

impl NostosConfig {
    /// Load `nostos.toml` from `path`. Returns a clear error (not a panic) if
    /// missing or malformed — every subcommand but `init` requires this file.
    pub fn load(path: &Path) -> Result<Self> {
        let text = std::fs::read_to_string(path).with_context(|| {
            format!(
                "no {} found at {} — run `nostos init` first",
                DEFAULT_FILE_NAME,
                path.display()
            )
        })?;
        toml::from_str(&text).with_context(|| format!("malformed {}", path.display()))
    }

    /// Serialize and write `nostos.toml`. Overwrites any existing file —
    /// re-running `nostos init` is expected to update the config in place.
    pub fn save(&self, path: &Path) -> Result<()> {
        let text = toml::to_string_pretty(self).context("serializing nostos.toml")?;
        let banner = "# nostos.toml — generated by `nostos init`. Safe to commit: no secrets live\n\
                       # here. The Postgres URL lives in .env (gitignored); see db.url_env.\n\n";
        std::fs::write(path, format!("{banner}{text}"))
            .with_context(|| format!("writing {}", path.display()))
    }

    /// The `NOSTOS_*` environment variables `nostos dev` passes to the
    /// `nostos-server` child process. Deliberately narrow: only vars
    /// `crates/nostos-server/src/main.rs` actually parses today. `pg_url` and
    /// `jwt_secret` come from `.env`, not this struct.
    #[must_use]
    pub fn server_env(&self, pg_url: &str, jwt_secret: Option<&str>) -> Vec<(String, String)> {
        let mut env = vec![
            ("NOSTOS_BIND".to_string(), self.server.bind.clone()),
            ("NOSTOS_WS_PATH".to_string(), self.server.ws_path.clone()),
            ("NOSTOS_REPLICATOR".to_string(), "pg".to_string()),
            ("NOSTOS_PG_URL".to_string(), pg_url.to_string()),
            ("NOSTOS_PG_SLOT".to_string(), self.db.slot.clone()),
            (
                "NOSTOS_PG_PUBLICATION".to_string(),
                self.db.publication.clone(),
            ),
            (
                "NOSTOS_WRITE_TABLES".to_string(),
                self.sync.write_tables.join(","),
            ),
        ];
        // The server only supports HS256 (NOSTOS_SUPABASE_JWT_SECRET) today —
        // RS256/ES256 JWKS verification is W2 (pending). Only flip on
        // supabase-jwt auth when a secret is actually present in .env;
        // otherwise stay `none` (anonymous, single-tenant dev default) rather
        // than emit a NOSTOS_SYNC_AUTH the server would reject/misconfigure.
        if let Some(secret) = jwt_secret.filter(|s| !s.is_empty()) {
            env.push(("NOSTOS_SYNC_AUTH".to_string(), "supabase-jwt".to_string()));
            env.push(("NOSTOS_SUPABASE_JWT_SECRET".to_string(), secret.to_string()));
            env.push((
                "NOSTOS_TENANT_COLUMN".to_string(),
                self.sync.tenant_column.clone(),
            ));
        }
        env
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> NostosConfig {
        NostosConfig {
            sync: SyncSection {
                tables: vec!["tasks".into(), "notes".into()],
                write_tables: vec!["tasks".into()],
                tenant_column: "org_id".into(),
            },
            db: DbSection::default(),
            supabase: Some(SupabaseSection {
                url: "https://xyz.supabase.co".into(),
                jwks_url: "https://xyz.supabase.co/auth/v1/.well-known/jwks.json".into(),
            }),
            server: ServerSection::default(),
        }
    }

    #[test]
    fn round_trips_through_toml() {
        let cfg = sample();
        let text = toml::to_string_pretty(&cfg).unwrap();
        let back: NostosConfig = toml::from_str(&text).unwrap();
        assert_eq!(cfg, back);
    }

    #[test]
    fn save_then_load_round_trips_via_disk() {
        let dir = std::env::temp_dir().join(format!("nostos-cli-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join(DEFAULT_FILE_NAME);
        let cfg = sample();
        cfg.save(&path).unwrap();
        let loaded = NostosConfig::load(&path).unwrap();
        assert_eq!(cfg, loaded);
        // Never write secrets into nostos.toml — url_env is a name, not a URL.
        let text = std::fs::read_to_string(&path).unwrap();
        assert!(!text.contains("postgres://"));
        assert!(!text.contains("postgresql://"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn minimal_toml_fills_defaults() {
        let text = "[sync]\ntables = [\"tasks\"]\n";
        let cfg: NostosConfig = toml::from_str(text).unwrap();
        assert_eq!(cfg.sync.tenant_column, "org_id");
        assert_eq!(cfg.db.publication, "cairn_pub");
        assert_eq!(cfg.db.slot, "cairn_slot");
        assert_eq!(cfg.server.bind, "0.0.0.0:8800");
        assert!(cfg.supabase.is_none());
    }

    #[test]
    fn server_env_omits_auth_vars_without_a_secret() {
        let cfg = sample();
        let env = cfg.server_env("postgresql://u:p@h/db", None);
        assert!(env
            .iter()
            .any(|(k, v)| k == "NOSTOS_PG_URL" && v.contains("postgresql://")));
        assert!(env
            .iter()
            .any(|(k, v)| k == "NOSTOS_REPLICATOR" && v == "pg"));
        assert!(env
            .iter()
            .any(|(k, v)| k == "NOSTOS_WRITE_TABLES" && v == "tasks"));
        assert!(!env.iter().any(|(k, _)| k == "NOSTOS_SYNC_AUTH"));
        assert!(!env.iter().any(|(k, _)| k == "NOSTOS_SUPABASE_JWT_SECRET"));
    }

    #[test]
    fn server_env_includes_auth_vars_with_a_secret() {
        let cfg = sample();
        let env = cfg.server_env("postgresql://u:p@h/db", Some("shh"));
        assert!(env
            .iter()
            .any(|(k, v)| k == "NOSTOS_SYNC_AUTH" && v == "supabase-jwt"));
        assert!(env
            .iter()
            .any(|(k, v)| k == "NOSTOS_SUPABASE_JWT_SECRET" && v == "shh"));
        assert!(env
            .iter()
            .any(|(k, v)| k == "NOSTOS_TENANT_COLUMN" && v == "org_id"));
    }
}
