//! `nostos deploy --template fly|railway` — generate a self-host deploy
//! config + `DEPLOY.md` from `nostos.toml`. Bare `nostos deploy` (no
//! template) prints the managed-deploy waitlist pointer; no infra is
//! provisioned pre-launch (W8).

use std::fmt::Write as _;
use std::path::Path;

use anyhow::{Context, Result};
use clap::{Args, ValueEnum};

use crate::config::{NostosConfig, DEFAULT_FILE_NAME};

#[derive(Debug, Clone, Copy, ValueEnum)]
pub enum Template {
    Fly,
    Railway,
}

#[derive(Debug, Clone, Copy, Args)]
pub struct DeployArgs {
    #[arg(long, value_enum)]
    pub template: Option<Template>,
}

pub fn run(args: DeployArgs, cwd: &Path) -> Result<()> {
    let Some(template) = args.template else {
        println!(
            "Managed deploy (zero-infra, no template needed) is on the waitlist — see the \
             README's Managed Deploy section to join."
        );
        return Ok(());
    };

    let cfg = NostosConfig::load(&cwd.join(DEFAULT_FILE_NAME))?;
    match template {
        Template::Fly => write_fly(&cfg, cwd),
        Template::Railway => write_railway(&cfg, cwd),
    }
}

fn write_fly(cfg: &NostosConfig, cwd: &Path) -> Result<()> {
    let port = cfg.server.bind.rsplit(':').next().unwrap_or("8800");
    let fly_toml = format!(
        "# generated by `nostos deploy --template fly` from nostos.toml\n\
         app = \"nostos-sync\"      # rename to a globally-unique Fly app name\n\
         primary_region = \"iad\"  # pick the region closest to your Postgres\n\n\
         [build]\n\
         dockerfile = \"Dockerfile\"\n\n\
         [env]\n\
         NOSTOS_BIND = \"0.0.0.0:{port}\"\n\
         NOSTOS_WS_PATH = \"{ws_path}\"\n\
         NOSTOS_REPLICATOR = \"pg\"\n\
         NOSTOS_PG_SLOT = \"{slot}\"\n\
         NOSTOS_PG_PUBLICATION = \"{publication}\"\n\
         NOSTOS_WRITE_TABLES = \"{write_tables}\"\n\
         # NOSTOS_PG_URL and NOSTOS_SUPABASE_JWT_SECRET are secrets — set them\n\
         # with `fly secrets set`, never here (see DEPLOY.md).\n\n\
         [[services]]\n\
         internal_port = {port}\n\
         protocol = \"tcp\"\n\n\
         [[services.ports]]\n\
         port = 443\n\
         handlers = [\"tls\", \"http\"]\n",
        ws_path = cfg.server.ws_path,
        slot = cfg.db.slot,
        publication = cfg.db.publication,
        write_tables = cfg.sync.write_tables.join(","),
    );
    std::fs::write(cwd.join("fly.toml"), fly_toml).context("writing fly.toml")?;
    write_deploy_md(
        cfg,
        cwd,
        "fly",
        &[
            "fly launch --no-deploy   # accept the generated fly.toml, skip auto-deploy",
            "fly secrets set NOSTOS_PG_URL=postgresql://... NOSTOS_SUPABASE_JWT_SECRET=...   # values from .env — never commit them",
            "fly deploy",
        ],
    )?;
    println!("\u{2713} wrote fly.toml and DEPLOY.md");
    Ok(())
}

fn write_railway(cfg: &NostosConfig, cwd: &Path) -> Result<()> {
    let port = cfg.server.bind.rsplit(':').next().unwrap_or("8800");
    let railway_json = serde_json::json!({
        "$schema": "https://railway.app/railway.schema.json",
        "build": {
            "builder": "DOCKERFILE",
            "dockerfilePath": "Dockerfile"
        },
        "deploy": {
            "startCommand": "nostos-server",
            "restartPolicyType": "ON_FAILURE"
        },
        // Non-secret env — NOSTOS_PG_URL / NOSTOS_SUPABASE_JWT_SECRET are set
        // as Railway "Variables" (secrets), never committed here.
        "environments": {
            "production": {
                "NOSTOS_BIND": format!("0.0.0.0:{port}"),
                "NOSTOS_WS_PATH": cfg.server.ws_path,
                "NOSTOS_REPLICATOR": "pg",
                "NOSTOS_PG_SLOT": cfg.db.slot,
                "NOSTOS_PG_PUBLICATION": cfg.db.publication,
                "NOSTOS_WRITE_TABLES": cfg.sync.write_tables.join(","),
            }
        }
    });
    let text = serde_json::to_string_pretty(&railway_json).context("serializing railway.json")?;
    std::fs::write(cwd.join("railway.json"), text).context("writing railway.json")?;
    write_deploy_md(
        cfg,
        cwd,
        "railway",
        &[
            "railway init   # accept the generated railway.json",
            "railway variables set NOSTOS_PG_URL=postgresql://... NOSTOS_SUPABASE_JWT_SECRET=...   # values from .env — never commit them",
            "railway up",
        ],
    )?;
    println!("\u{2713} wrote railway.json and DEPLOY.md");
    Ok(())
}

fn write_deploy_md(cfg: &NostosConfig, cwd: &Path, platform: &str, steps: &[&str]) -> Result<()> {
    let mut md = format!(
        "# Deploying nostos-server to {platform}\n\nGenerated by `nostos deploy --template {platform}` from nostos.toml.\n\n"
    );
    md.push_str("## Non-secret env (baked into the generated config)\n\n");
    let _ = writeln!(md, "- `NOSTOS_PG_SLOT={}`", cfg.db.slot);
    let _ = writeln!(md, "- `NOSTOS_PG_PUBLICATION={}`", cfg.db.publication);
    let _ = writeln!(
        md,
        "- `NOSTOS_WRITE_TABLES={}`",
        cfg.sync.write_tables.join(",")
    );
    md.push_str("\n## Secrets — set on the platform, never in the repo\n\n");
    md.push_str("- `NOSTOS_PG_URL` — your Postgres connection string (see .env)\n");
    md.push_str("- `NOSTOS_SUPABASE_JWT_SECRET` — only if NOSTOS_SYNC_AUTH=supabase-jwt\n");
    md.push_str("\n## Steps\n\n");
    for (i, step) in steps.iter().enumerate() {
        let _ = writeln!(md, "{}. `{step}`", i + 1);
    }
    md.push_str(
        "\nReference: `Dockerfile` at the repo root builds `nostos-server` with the `pg` feature.\n",
    );
    std::fs::write(cwd.join("DEPLOY.md"), md).context("writing DEPLOY.md")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{DbSection, ServerSection, SyncSection};

    fn sample_cfg() -> NostosConfig {
        NostosConfig {
            sync: SyncSection {
                tables: vec!["tasks".into()],
                write_tables: vec!["tasks".into()],
                tenant_column: "org_id".into(),
            },
            db: DbSection {
                url_env: "NOSTOS_PG_URL".into(),
                publication: "cairn_pub".into(),
                slot: "cairn_slot".into(),
            },
            supabase: None,
            server: ServerSection {
                bind: "0.0.0.0:8800".into(),
                ws_path: "/sync".into(),
            },
        }
    }

    fn temp_dir(label: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "nostos-cli-deploy-test-{label}-{}",
            std::process::id()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn fly_template_writes_toml_and_deploy_md_with_expected_content() {
        let cfg = sample_cfg();
        let dir = temp_dir("fly");

        write_fly(&cfg, &dir).unwrap();

        let fly_toml = std::fs::read_to_string(dir.join("fly.toml")).unwrap();
        assert!(fly_toml.contains("NOSTOS_PG_PUBLICATION = \"cairn_pub\""));
        assert!(fly_toml.contains("NOSTOS_PG_SLOT = \"cairn_slot\""));
        assert!(fly_toml.contains("NOSTOS_WRITE_TABLES = \"tasks\""));
        assert!(fly_toml.contains("8800"));
        // Never leak a placeholder for the real secret.
        assert!(!fly_toml.contains("NOSTOS_PG_URL ="));

        let deploy_md = std::fs::read_to_string(dir.join("DEPLOY.md")).unwrap();
        assert!(deploy_md.contains("fly launch"));
        assert!(deploy_md.contains("NOSTOS_PG_URL"));

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn railway_template_writes_valid_json_and_deploy_md() {
        let cfg = sample_cfg();
        let dir = temp_dir("railway");

        write_railway(&cfg, &dir).unwrap();

        let text = std::fs::read_to_string(dir.join("railway.json")).unwrap();
        let parsed: serde_json::Value =
            serde_json::from_str(&text).expect("railway.json must be valid JSON");
        assert_eq!(
            parsed["environments"]["production"]["NOSTOS_PG_PUBLICATION"],
            "cairn_pub"
        );
        assert_eq!(
            parsed["environments"]["production"]["NOSTOS_WRITE_TABLES"],
            "tasks"
        );
        assert_eq!(parsed["build"]["dockerfilePath"], "Dockerfile");

        let deploy_md = std::fs::read_to_string(dir.join("DEPLOY.md")).unwrap();
        assert!(deploy_md.contains("railway init"));
        assert!(deploy_md.contains("NOSTOS_SUPABASE_JWT_SECRET"));

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn bare_deploy_prints_waitlist_and_touches_nothing() {
        let dir = temp_dir("waitlist");
        let args = DeployArgs { template: None };
        run(args, &dir).unwrap();
        assert!(!dir.join("nostos.toml").exists());
        assert!(!dir.join("fly.toml").exists());
        assert!(!dir.join("railway.json").exists());
        std::fs::remove_dir_all(&dir).ok();
    }
}
