//! `nostos gen` — app-side: read `.nostos/{config,schema}.json` and emit per-SDK
//! generated source. Flutter target (default + only v1 SDK): `lib/nostos.g.dart`
//! with a `NostosConfig` const, a `NostosSchema` const, and one typed model
//! class per table. See ADR-0023 D2.
//!
//! Ponytail: no new deps — the Dart source is built with `std::fmt::Write`
//! into a `String` (writes to `String` are infallible; the `?` on `writeln!`
//! propagates a `std::fmt::Error` that is never actually produced).

use std::fmt::Write as _;
use std::path::Path;

use anyhow::{bail, Context, Result};
use clap::Args;
use serde_json::Value;

use crate::config::{dot_dir, Backend, ProjectConfig, SCHEMA_JSON};

#[derive(Debug, Args)]
pub struct GenArgs {
    /// Target SDK: `flutter` (default; `typescript` is post-v1).
    #[arg(long, default_value = "flutter")]
    pub sdk: String,
    /// Output path (Flutter: a `.dart` file, default `lib/nostos.g.dart`).
    #[arg(long, default_value = "lib/nostos.g.dart")]
    pub out: String,
}

/// Entry point for `nostos gen`.
///
/// # Errors
/// [`anyhow::Error`] if `sdk` is not `flutter`, if `.nostos/{config,schema}.json`
/// are missing/malformed, or if the generated file cannot be written.
#[allow(clippy::unused_async)] // main.rs dispatches every command via `.await`.
pub async fn run(args: GenArgs, cwd: &Path) -> Result<()> {
    if args.sdk != "flutter" {
        bail!(
            "only flutter is supported in v1 (sdk={sdk})",
            sdk = args.sdk
        );
    }

    let config = ProjectConfig::load(cwd)?;

    let schema_path = dot_dir(cwd).join(SCHEMA_JSON);
    if !schema_path.exists() {
        bail!("no .nostos/schema.json — run nostos pull first");
    }
    let schema_text = std::fs::read_to_string(&schema_path)
        .with_context(|| format!("reading {}", schema_path.display()))?;
    let schema: Value = serde_json::from_str(&schema_text)
        .with_context(|| format!("malformed {}", schema_path.display()))?;

    let table_count = schema
        .get("tables")
        .and_then(|t| t.as_array())
        .map_or(0, Vec::len);

    let dart = generate_dart(&config, &schema)?;

    let out_path = cwd.join(&args.out);
    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    std::fs::write(&out_path, dart).with_context(|| format!("writing {}", out_path.display()))?;

    println!(
        "✓ wrote {out} ({n} tables)",
        out = args.out,
        n = table_count
    );
    println!(
        "wire it: final db = await NostosDatabase.open(config: nostosConfig, schema: nostosSchema, sqliteDir: dir);"
    );
    Ok(())
}

/// Render the full `lib/nostos.g.dart` source for a project + server schema.
///
/// # Errors
/// [`anyhow::Error`] if the schema is missing required `tables`/`name`/
/// `columns` fields (server-produced schemas always have them; a malformed
/// file fails loudly rather than emitting partial Dart).
fn generate_dart(config: &ProjectConfig, schema: &Value) -> Result<String> {
    let mut out = String::new();
    writeln!(
        out,
        "// GENERATED by `nostos gen` — do not edit. Regenerate with `nostos pull && nostos gen`."
    )?;
    writeln!(out, "import 'package:nostos_flutter/nostos_flutter.dart';")?;
    writeln!(out)?;

    // NostosConfig — supabase lines only when the backend preset is Supabase.
    writeln!(out, "const nostosConfig = NostosConfig(")?;
    writeln!(out, "  url: '{}',", escape_dart_string(&config.sync_url))?;
    if let Some(Backend::Supabase { url, anon_key }) = &config.backend {
        writeln!(out, "  supabaseUrl: '{}',", escape_dart_string(url))?;
        writeln!(
            out,
            "  supabaseAnonKey: '{}',",
            escape_dart_string(anon_key)
        )?;
    }
    writeln!(out, ");")?;
    writeln!(out)?;

    // NostosSchema — one NostosTable per table, in publication order.
    let tables = schema
        .get("tables")
        .and_then(|t| t.as_array())
        .ok_or_else(|| anyhow::anyhow!("schema has no \"tables\" array"))?;

    writeln!(out, "const nostosSchema = NostosSchema(tables: [")?;
    for table in tables {
        let name = table
            .get("name")
            .and_then(|v| v.as_str())
            .ok_or_else(|| anyhow::anyhow!("table missing \"name\""))?;
        let pk: Vec<String> = table
            .get("primary_key")
            .and_then(|v| v.as_array())
            .map(|a| {
                a.iter()
                    .filter_map(|x| x.as_str())
                    .map(String::from)
                    .collect()
            })
            .unwrap_or_default();
        let pk_list = pk
            .iter()
            .map(|p| format!("'{}'", escape_dart_string(p)))
            .collect::<Vec<_>>()
            .join(", ");
        let name_esc = escape_dart_string(name);
        writeln!(
            out,
            "  NostosTable(name: '{name_esc}', primaryKey: [{pk_list}], columns: [",
        )?;

        let columns = table
            .get("columns")
            .and_then(|v| v.as_array())
            .ok_or_else(|| anyhow::anyhow!("table missing \"columns\""))?;
        for col in columns {
            let cname = col
                .get("name")
                .and_then(|v| v.as_str())
                .ok_or_else(|| anyhow::anyhow!("column missing \"name\""))?;
            let aff = col.get("affinity").and_then(|v| v.as_str()).unwrap_or("");
            let esc = escape_dart_string(cname);
            writeln!(
                out,
                "    NostosColumn.{ctor}('{esc}'),",
                ctor = affinity_ctor(aff),
            )?;
        }
        writeln!(out, "  ]),")?;
    }
    writeln!(out, "]);")?;
    writeln!(out)?;

    // One typed model per table.
    for table in tables {
        write_model(&mut out, table)?;
        writeln!(out)?;
    }

    Ok(out)
}

/// Append the typed model class for one table to `out`.
///
/// # Errors
/// [`anyhow::Error`] if the table object is missing `name` or `columns`.
fn write_model(out: &mut String, table: &Value) -> Result<()> {
    let name = table
        .get("name")
        .and_then(|v| v.as_str())
        .ok_or_else(|| anyhow::anyhow!("table missing \"name\""))?;
    let class_name = pascal_case(name);

    let pk: Vec<String> = table
        .get("primary_key")
        .and_then(|v| v.as_array())
        .map(|a| {
            a.iter()
                .filter_map(|x| x.as_str())
                .map(String::from)
                .collect()
        })
        .unwrap_or_default();
    let columns = table
        .get("columns")
        .and_then(|v| v.as_array())
        .ok_or_else(|| anyhow::anyhow!("table missing \"columns\""))?;

    // The primary key is modeled as a single non-nullable String field. The
    // Dart field name is lowerCamelCase (snake `user_id` → `userId`); the
    // row-map key stays the original snake_case column name. Composite-pk
    // 2nd+ columns are deliberately not modeled as fields in v1.
    let first_pk = pk.first().cloned();
    let id_key = first_pk.clone().unwrap_or_else(|| "id".to_string());
    let id_field = snake_to_camel(&id_key);

    // (row key [snake], Dart field [camel], affinity) for each non-pk column.
    let non_pk: Vec<(String, String, String)> = columns
        .iter()
        .filter_map(|c| {
            let n = c.get("name").and_then(|v| v.as_str())?;
            if pk.iter().any(|p| p == n) {
                return None;
            }
            let aff = c
                .get("affinity")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();
            Some((n.to_string(), snake_to_camel(n), aff))
        })
        .collect();

    writeln!(out, "class {class_name} {{")?;

    let mut params = vec![format!("required this.{id_field}")];
    for (_, field, _) in &non_pk {
        params.push(format!("this.{field}"));
    }
    writeln!(out, "  const {class_name}({{{}}});", params.join(", "))?;

    writeln!(out, "  final String {id_field};")?;
    for (_, field, aff) in &non_pk {
        writeln!(out, "  final {ty} {field};", ty = affinity_dart_type(aff))?;
    }
    writeln!(out)?;

    // fromRow: `_pk` is the stamped row key the WS2 read-view exposes. Row
    // keys stay snake_case (catalog column names); Dart fields are camel.
    let id_expr = match &first_pk {
        Some(col) => format!(
            "(r['_pk'] ?? r['{key}']).toString()",
            key = escape_dart_string(col),
        ),
        None => "(r['_pk']).toString()".to_string(),
    };
    writeln!(
        out,
        "  factory {class_name}.fromRow(Map<String, dynamic> r) => {class_name}(",
    )?;
    writeln!(out, "    {id_field}: {id_expr},")?;
    for (key, field, aff) in &non_pk {
        let expr = from_row_expr(aff, key);
        writeln!(out, "    {field}: {expr},")?;
    }
    writeln!(out, "  );")?;

    // toPayload: every column (including pk), snake_case keys, camel fields.
    writeln!(out)?;
    writeln!(out, "  Map<String, dynamic> toPayload() => {{")?;
    for col in columns {
        let cn = col
            .get("name")
            .and_then(|v| v.as_str())
            .ok_or_else(|| anyhow::anyhow!("column missing \"name\""))?;
        if Some(cn) == first_pk.as_deref() {
            writeln!(
                out,
                "    '{key}': {id_field},",
                key = escape_dart_string(cn)
            )?;
        } else if !pk.iter().any(|p| p == cn) {
            let field = snake_to_camel(cn);
            writeln!(out, "    '{key}': {field},", key = escape_dart_string(cn))?;
        }
        // else: composite-pk 2nd+ column has no field in v1 — skipped.
    }
    writeln!(out, "  }};")?;

    writeln!(out, "}}")?;
    Ok(())
}

/// Map a column affinity to its `NostosColumn` constructor name.
fn affinity_ctor(aff: &str) -> &'static str {
    match aff {
        "INTEGER" => "integer",
        "REAL" => "real",
        _ => "text",
    }
}

/// Map a column affinity to its Dart field type (nullable).
fn affinity_dart_type(aff: &str) -> &'static str {
    match aff {
        "INTEGER" => "int?",
        "REAL" => "double?",
        _ => "String?",
    }
}

/// Build the Dart `fromRow` RHS for one column, keyed by `col`.
fn from_row_expr(aff: &str, col: &str) -> String {
    let e = escape_dart_string(col);
    match aff {
        "INTEGER" => format!("r['{e}'] is int ? r['{e}'] : int.tryParse('${{r['{e}']}}')"),
        "REAL" => format!(
            "r['{e}'] is num ? (r['{e}'] as num).toDouble() : double.tryParse('${{r['{e}']}}')"
        ),
        _ => format!("r['{e}']?.toString()"),
    }
}

/// Convert a table name to a PascalCase, singularized model class name:
/// `providers` → `Provider`, `availabilities` → `Availability`,
/// `appointment_items` → `AppointmentItem`. Singularization is handled by
/// [`singularize`] first, then the result is PascalCased.
fn pascal_case(name: &str) -> String {
    let singular = singularize(name);
    let mut joined = String::new();
    for part in singular.split('_') {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            joined.extend(first.to_uppercase());
            joined.extend(chars.flat_map(char::to_lowercase));
        }
    }
    joined
}

/// Naive English singularizer covering the conventional catalog plurals:
/// `ies` → `y` (`availabilities` → `availability`, `categories` →
/// `category`), `ses`/`xes`/`zes` → drop `es` (`addresses` → `address`,
/// `boxes` → `box`), plain `s` → drop `s` (`providers` → `provider`); `ss`
/// is preserved (`address`, `class`). English singularization is irregular;
/// this handles the common Rails/Supabase table-name families and is a
/// deliberate v1 ceiling (`data`/`media`/`children` stay as-is).
///
/// Catalog identifiers are ASCII (nostos's identifier handling assumes this),
/// so byte-slicing is safe here.
fn singularize(word: &str) -> String {
    let lower = word.to_ascii_lowercase();
    if lower.ends_with("ies") && word.len() > 3 {
        format!("{}y", &word[..word.len() - 3])
    } else if lower.ends_with("ses") || lower.ends_with("xes") || lower.ends_with("zes") {
        word[..word.len() - 2].to_string()
    } else if lower.ends_with('s') && !lower.ends_with("ss") {
        word[..word.len() - 1].to_string()
    } else {
        word.to_string()
    }
}

/// Convert a snake_case column name to a lowerCamelCase Dart field name
/// (`provider_id` → `providerId`, `duration_min` → `durationMin`, `id` →
/// `id`). Dart style is lowerCamelCase for fields; the snake_case name
/// survives only as the row-map key in `fromRow` / `toPayload`.
fn snake_to_camel(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut up_next = false;
    for ch in s.chars() {
        if ch == '_' {
            up_next = true;
        } else if up_next {
            out.extend(ch.to_uppercase());
            up_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

/// Escape `\` and `'` so a name embeds safely inside a single-quoted Dart
/// string literal. Names are trusted catalog data, but be safe.
fn escape_dart_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            c => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gen_emits_typed_schema_and_model() {
        let config = ProjectConfig {
            mode: crate::config::LinkMode::default(),
            project: "demo".to_string(),
            sync_url: "ws://127.0.0.1:8800/sync".to_string(),
            backend: Some(Backend::Supabase {
                url: "https://xyz.supabase.co".to_string(),
                anon_key: "eyfake".to_string(),
            }),
        };
        let schema_json = r#"{
            "publication": "cairn_pub",
            "tables": [
                { "name": "providers", "primary_key": ["id"],
                  "columns": [
                    {"name":"id","pg_oid":25,"affinity":"TEXT"},
                    {"name":"name","pg_oid":25,"affinity":"TEXT"},
                    {"name":"weekday","pg_oid":23,"affinity":"INTEGER"},
                    {"name":"rate","pg_oid":701,"affinity":"REAL"},
                    {"name":"created_by","pg_oid":25,"affinity":"TEXT"}
                  ] }
            ]
        }"#;
        let schema: Value = serde_json::from_str(schema_json).unwrap();
        let dart = generate_dart(&config, &schema).expect("gen should succeed");

        assert!(
            dart.contains("NostosTable(name: 'providers'"),
            "providers table"
        );
        assert!(dart.contains("NostosColumn.text('id')"), "id -> text ctor");
        assert!(
            dart.contains("NostosColumn.integer('weekday')"),
            "weekday -> integer ctor"
        );
        assert!(
            dart.contains("NostosColumn.real('rate')"),
            "rate -> real ctor"
        );
        assert!(dart.contains("class Provider"), "pascal_case + singularize");
        assert!(
            dart.contains("supabaseUrl: 'https://xyz.supabase.co'"),
            "supabase url line"
        );
        assert!(dart.contains("final int? weekday;"), "integer -> int?");
        assert!(dart.contains("final double? rate;"), "real -> double?");
        assert!(
            dart.contains("int.tryParse('${r['weekday']}')"),
            "integer fromRow coercion"
        );
        assert!(dart.contains("primaryKey: ['id']"), "pk list literal");
        // snake_case column → camelCase Dart field, snake_case row key.
        assert!(
            dart.contains("final String? createdBy;"),
            "created_by -> createdBy field"
        );
        assert!(
            dart.contains("createdBy: r['created_by']?.toString()"),
            "fromRow maps snake key to camel field"
        );
        assert!(
            dart.contains("'created_by': createdBy,"),
            "toPayload keeps snake key, camel field"
        );
    }

    #[test]
    fn snake_to_camel_converts_field_names() {
        assert_eq!(snake_to_camel("provider_id"), "providerId");
        assert_eq!(snake_to_camel("duration_min"), "durationMin");
        assert_eq!(snake_to_camel("starts_at"), "startsAt");
        assert_eq!(snake_to_camel("id"), "id");
    }

    #[test]
    fn pascal_case_singularizes_table_names() {
        assert_eq!(pascal_case("providers"), "Provider");
        assert_eq!(pascal_case("appointment_items"), "AppointmentItem");
        assert_eq!(pascal_case("address"), "Address"); // 'ss' guard
        assert_eq!(pascal_case("user"), "User"); // no trailing 's'
        assert_eq!(pascal_case("availabilities"), "Availability"); // 'ies' → 'y'
        assert_eq!(pascal_case("categories"), "Category");
        assert_eq!(pascal_case("invoices"), "Invoice");
        assert_eq!(pascal_case("addresses"), "Address"); // 'ses' → drop 'es'
    }

    #[test]
    fn gen_omits_supabase_for_plain_postgres() {
        let config = ProjectConfig {
            mode: crate::config::LinkMode::default(),
            project: "demo".to_string(),
            sync_url: "ws://127.0.0.1:8800/sync".to_string(),
            backend: None,
        };
        let schema: Value =
            serde_json::from_str(r#"{ "publication": "p", "tables": [] }"#).unwrap();
        let dart = generate_dart(&config, &schema).expect("gen should succeed");
        assert!(
            !dart.contains("supabaseUrl"),
            "no supabase block for plain Postgres"
        );
        assert!(dart.contains("const nostosConfig = NostosConfig("));
        assert!(dart.contains("NostosSchema(tables: ["));
    }
}
