// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'nostos.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `abort_pumps`, `abort_run`, `emit_rows`, `emit_status`, `enqueue`, `track`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NostosAppwriteHandle>>
abstract class NostosAppwriteHandle implements RustOpaqueInterface {
  void applySchema({required List<ClientTableFfi> tables});

  Future<void> close();

  /// Open one provider-scoped SQLite file and bind a signed-in Appwrite user.
  /// No network call is made before `start` or `sync_now`.
  static NostosAppwriteHandle connect({
    required String endpoint,
    required String projectId,
    required String functionId,
    required String userId,
    required String jwt,
    required String dbPath,
  }) => RustLib.instance.api.crateApiAppwriteNostosAppwriteHandleConnect(
    endpoint: endpoint,
    projectId: projectId,
    functionId: functionId,
    userId: userId,
    jwt: jwt,
    dbPath: dbPath,
  );

  Future<void> disconnect();

  Future<String> query({required String sql});

  Stream<NostosConnectionState> resume();

  /// Rotate a short-lived JWT; `None` pauses authenticated sync.
  Future<void> setToken({String? token});

  /// Bind a different account, clearing the previous principal's rows and outbox.
  Future<void> setUser({required String userId, required String jwt});

  Future<void> signOut();

  Stream<NostosConnectionState> start();

  Future<BigInt> syncNow();

  Stream<String> watch({required String table});

  Stream<WriteQueueStatusFfi> watchWriteStatus();

  Future<BigInt> write({
    required String table,
    required String op,
    required String pk,
    String? payloadJson,
  });

  Future<Uint64List> writeBatch({required List<NostosWriteInput> ops});
}
