// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'nostos.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `abort_pumps`, `abort_run`, `emit_rows`, `emit_status`, `enqueue`, `kick`, `spawn_run`, `track`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NostosDirectHandle>>
abstract class NostosDirectHandle implements RustOpaqueInterface {
  /// Materialize the read-views for `tables` in the device's SQLite file, as
  /// [`crate::api::nostos::NostosHandle::apply_schema`] does. Idempotent.
  ///
  /// # Errors
  /// Any view DDL that fails.
  void applySchema({required List<ClientTableFfi> tables});

  /// Stop the loop and every pump. The database and its outbox stay on disk,
  /// so a later `connect` resumes from the same horizon.
  Future<void> close();

  /// Open the device's database and point it at a Supabase project. Touches
  /// no network until [`Self::start`] or [`Self::sync_now`].
  ///
  /// `supabase_url` is the project URL (`https://<ref>.supabase.co`),
  /// `anon_key` its publishable key — the only credential that ships inside
  /// the app, and the reason direct mode needs RLS rather than trust.
  ///
  /// # Errors
  /// The SQLite file cannot be opened or migrated, or `supabase_url` is not a
  /// usable PostgREST base.
  static NostosDirectHandle connect({
    required String supabaseUrl,
    required String anonKey,
    String? token,
    required String dbPath,
  }) => RustLib.instance.api.crateApiDirectNostosDirectHandleConnect(
    supabaseUrl: supabaseUrl,
    anonKey: anonKey,
    token: token,
    dbPath: dbPath,
  );

  /// Stop syncing without losing the device: the loop is aborted, `watch`
  /// streams and writes keep working offline. Pair with [`Self::resume`].
  /// Idempotent.
  Future<void> disconnect();

  /// Add `delta` to `field` through the generated `cairn_increment` — the one
  /// write Postgres serializes for us, so two devices incrementing the same
  /// row sum instead of clobbering (ADR-0030, direct-mode plan step 5).
  ///
  /// # Errors
  /// As [`Self::write`].
  Future<BigInt> increment({
    required String table,
    required String pk,
    required String field,
    required double delta,
  });

  /// Run read-only SQL against the device's own database, returning a JSON
  /// array of row objects.
  ///
  /// # Errors
  /// The SQL failed to prepare, or a row failed to decode.
  Future<String> query({required String sql});

  /// Resume syncing after [`Self::disconnect`], on the scope [`Self::start`]
  /// was given. The outbox flushes on the first sync.
  ///
  /// # Errors
  /// [`Self::start`] was never called, or a loop is already running.
  Stream<NostosConnectionState> resume();

  /// Present `token` as the signed-in user. Direct mode has no session to
  /// renegotiate, so this takes effect on the next pull — call it whenever
  /// Supabase refreshes the JWT, and nothing the UI is holding tears down.
  Future<void> setToken({String? token});

  /// Sign out (ADR-0029): stop syncing, drop the token, and wipe local rows,
  /// the outbox and the horizon — everything the next principal must not see.
  ///
  /// The pumps stop FIRST so no watch re-reads the database halfway through
  /// the delete.
  ///
  /// # Errors
  /// The wipe failed. The token is dropped either way, so a failed sign-out
  /// cannot leave the device still pulling as the old user.
  Future<void> signOut();

  /// Start syncing: pull now, then on every doorbell ring and every
  /// reconnect, until [`Self::disconnect`] or [`Self::close`].
  ///
  /// `scope` is the value the change-log trigger stamps — `sub:<user-uuid>`
  /// for a user-scoped app, which is also the private Realtime channel the
  /// device is allowed to join.
  ///
  /// The state stream reports what the loop is doing: `connected` after a
  /// sync that reached the project, `reconnecting` after one that did not.
  /// There is no socket to be "connecting" on before the first pull, so the
  /// first value comes from the first sync rather than ahead of it.
  ///
  /// # Errors
  /// A loop is already running.
  Stream<NostosConnectionState> start({required String scope});

  /// Push the outbox and pull once, now. What [`Self::start`]'s loop does on
  /// a ring — for a pull-to-refresh, or a test.
  ///
  /// # Errors
  /// Whatever the round trip failed with.
  Future<BigInt> syncNow();

  /// Stream `table`'s rows as a JSON array string, re-emitted on every change
  /// — local write or applied sync.
  ///
  /// Emits immediately from durable storage, before any network: rows from a
  /// previous run must render offline, not only after the first pull.
  ///
  /// # Errors
  /// Never, currently — the signature matches server mode's `watch` so the
  /// two Dart engines stay interchangeable.
  Stream<String> watch({required String table});

  /// Stream durable-outbox status: queued writes, permanently-failed writes,
  /// and the message the server gave for the last permanent failure.
  ///
  /// Emits the current value immediately, because writes queued in a previous
  /// run are already pending at construction — a status widget built later in
  /// the app's life must render the true count rather than wait for a change
  /// that may never come offline.
  ///
  /// # Errors
  /// Never, currently — matches server mode's signature.
  Stream<WriteQueueStatusFfi> watchWriteStatus();

  /// Queue one write. Returns once it is durable on the device; the push to
  /// PostgREST runs behind it, so a write made offline is kept, not lost.
  ///
  /// # Errors
  /// An unknown `op`, or an outbox that would not commit.
  Future<BigInt> write({
    required String table,
    required String op,
    required String pk,
    String? payloadJson,
  });

  /// Queue a batch atomically — all of it lands in one SQLite transaction or
  /// none of it does (ADR-0032 T3). Ids come back in the order given.
  ///
  /// # Errors
  /// As [`Self::write`]; one bad op rejects the whole batch before the outbox
  /// is touched.
  Future<Uint64List> writeBatch({required List<NostosWriteInput> ops});
}
