// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `emit_snapshot`, `hex_encode`, `lock_session`, `row_to_json_object`, `run_connection_loop`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Session`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `drop`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NostosHandle>>
abstract class NostosHandle implements RustOpaqueInterface {
  /// Materialize the WS2 read-views for `tables` in the on-device SQLite
  /// file (`CREATE VIEW IF NOT EXISTS <table> AS SELECT json_extract(...) AS
  /// col, ... FROM cairn_data WHERE table_name = '<table>'` — see
  /// `SqliteStorage::apply_schema`). Idempotent for an unchanged schema; the
  /// views persist in the SQLite file, so this is called ONCE after `connect`
  /// (and before the first `query()` / Dart `db.execute(SELECT ...)` that
  /// names a table).
  ///
  /// Opens a TRANSIENT storage connection at `db_path` (separate from the
  /// `subscribe` session's) purely to run the DDL, then drops it.
  /// ponytail: the transient double-open is a one-time setup cost (cheap);
  /// the upgrade path is to stash the schema on the handle and apply it
  /// inside `subscribe` on the session's own connection — deferred because
  /// this is not on any hot path.
  ///
  /// The Dart side owns the `GET /schema` fetch + `SchemaDescriptor` →
  /// `ClientTableFfi` mapping, keeping the Rust FFI crate HTTP-free
  /// (ADR-0015: no `reqwest` dep in `nostos_flutter_rust`).
  ///
  /// # Errors
  /// Returns an error string if the SQLite file can't be opened/migrated or
  /// any view DDL fails (`StorageError::Backend`).
  void applySchema({required List<ClientTableFfi> tables});

  /// Tear down the active subscription's background work — the
  /// connect/apply/reconnect loop and every watch pump (see [`Session`]'s
  /// `Drop` impl, which aborts all of them). Safe to call with no active
  /// subscription (a no-op) and safe to call more than once.
  ///
  /// Named `close`, not `dispose`: every `#[frb(opaque)]` handle already
  /// implements `RustOpaqueInterface`, which declares its own synchronous
  /// `void dispose()` for releasing the FFI handle itself — reusing that
  /// name here would collide with an unrelated method of a different
  /// signature (async vs sync). `close` mirrors `dart:io`'s
  /// `WebSocket.close()`, which this SDK's own session shape is closest to.
  ///
  /// This does NOT close the underlying SQLite file or shut down this
  /// handle's own tokio runtime — a subsequent `subscribe()` call on the
  /// SAME `NostosHandle` reopens a fresh session against the same durable
  /// store. The runtime itself is torn down when the handle is dropped
  /// (frb's generated `Drop` glue for an `#[frb(opaque)]` type, which is
  /// what `RustOpaqueInterface::dispose()` triggers), which happens once
  /// Dart releases its last reference — `close()` exists for a caller that
  /// wants to stop syncing sooner than that, e.g. a widget's `dispose()`
  /// lifecycle callback, rather than waiting on GC.
  Future<void> close();

  /// Open a connection. Does not touch the network yet — `subscribe()`
  /// starts the actual WebSocket session. `db_path` is the SQLite file the
  /// durable client state lives in (Dart picks the directory, e.g. via
  /// `path_provider`'s `getApplicationSupportDirectory()` — see the
  /// `nostos_flutter` Dart wrapper).
  static NostosHandle connect({
    required String url,
    String? token,
    required String dbPath,
  }) => RustLib.instance.api.crateApiNostosNostosHandleConnect(
    url: url,
    token: token,
    dbPath: dbPath,
  );

  /// Decrement the PN-Counter by `delta` (bumps the negative counter `n`).
  Future<BigInt> counterDecrement({
    required String table,
    required String pk,
    required BigInt delta,
  });

  /// Increment the PN-Counter in row `pk` of `table` by `delta` (ADR-0030
  /// addendum). Read-modify-write: reads the current counter payload, applies
  /// the delta to this replica's entry, and enqueues the result. The per-
  /// replica max merge converges across replicas.
  Future<BigInt> counterIncrement({
    required String table,
    required String pk,
    required PlatformInt64 delta,
  });

  Future<void> disconnect();

  /// Add `element` to the add-wins OR-set in row `pk` of `table` (ADR-0030 /
  /// ADR-0032 T4). Mints a client HLC and enqueues a merge-upsert. The
  /// element renders locally immediately and converges with concurrent
  /// remote adds on the server's echo.
  ///
  /// Requires the table to be tagged as an OR-set in the client config.
  Future<BigInt> orSetAdd({
    required String table,
    required String pk,
    required String element,
  });

  /// Remove `element` from the OR-set — a tombstone at a fresh HLC. Add-wins:
  /// a concurrent or later re-add re-activates the element.
  Future<BigInt> orSetRemove({
    required String table,
    required String pk,
    required String element,
  });

  /// Run an arbitrary `SELECT` against the on-device SQLite (the synced
  /// `cairn_data` table). Returns a JSON-array-of-objects STRING — one
  /// object per row, keyed by column name — which is the SAME shape the
  /// `rows` tick stream emits, so Dart decodes it identically with
  /// `jsonDecode`. The SQL typically uses
  /// `json_extract(payload, '$.col')` to project the opaque payload (JSON1
  /// ships in the bundled SQLite; ADR-0019) — e.g.
  /// `SELECT json_extract(payload, '$.title') AS title FROM cairn_data`.
  ///
  /// Requires an active subscription: the [`Session`] owns the
  /// [`SqliteStorage`] the client binds at `subscribe()` time, and
  /// `with_storage` reaches the concrete backend the same way `rows_for`
  /// does in `emit_snapshot` below (the closure param is `&SqliteStorage`,
  /// not `&Storage`, so `.query()` is callable in that position). Parity
  /// feature P1 — see `docs/plans/powersync-sdk-parity-plan.md`.
  ///
  /// This is a read-side accessor on the same `Mutex<Connection>` as the
  /// write path; it shares no mutation surface with the outbox (see the
  /// `Storage::query` doc in `nostos-core` for the trait-bound rationale).
  ///
  /// # Errors
  /// Returns an error string if `subscribe()` hasn't been called yet, the
  /// storage task panicked (`ClientError::Join`), or the SQL fails to
  /// prepare / a row fails to decode (`StorageError::Backend`).
  Future<String> query({required String sql});

  /// Resume syncing after [`disconnect`]: respawn the connect/apply/reconnect
  /// loop on the SAME `SyncClient` (reusable across aborts — `run_once(&self)`,
  /// all per-session state local, `tokio::sync::Mutex` carries no poison). The
  /// durable outbox drains on the new session's startup flush; live updates
  /// resume. `state_sink` receives the fresh run's transitions
  /// (`connecting → connected → …`). Requires a prior `subscribe()`.
  ///
  /// Named `resume`, not `connect`: the `#[frb(sync)]` constructor is already
  /// `NostosHandle::connect`, and Rust forbids two inherent items of the same
  /// name; the Dart public API mirrors the pause/resume pair (WS5) for the
  /// same reason — `connect` clashes with `Nostos.connect`/`NostosDatabase.connect`.
  Stream<NostosConnectionState> resume();

  /// Pause syncing: abort ONLY the connect/apply/reconnect loop, keeping the
  /// `SyncClient`, its `SqliteStorage`, and every `watch()` pump alive. Reads,
  /// writes (which land in the durable outbox), and the UI keep working
  /// offline. `resume()` restarts it. Idempotent: a no-op when already paused
  /// or when there is no active subscription.
  ///
  /// Emits nothing on `state_sink` here (the aborted loop leaves it mid
  /// `connecting`/`reconnecting`); the Dart wrapper surfaces `disconnected`
  /// so the UI signal has one owner. Cancellation is task-abort: `run_once`
  /// respects no stop token, and `tokio::sync::Mutex` (no poison) + `Arc`
  /// client state mean the client stays usable for local work after the abort.
  /// Replace the bearer token for subsequent connections (ADR-0010 auth).
  ///
  /// Call this when the auth provider rotates a token — for `supabase_flutter`
  /// that is `onAuthStateChange` firing `tokenRefreshed`. Without it a client
  /// keeps re-sending the token it was constructed with, the server rejects it
  /// on `exp`, and the reconnect loop retries a dead credential forever: the
  /// app renders stale rows and never syncs again.
  ///
  /// Updates BOTH the handle's seed (so a later `subscribe()` builds its config
  /// with the new value) and the live `SyncClient` if a session already exists.
  /// Missing either half leaves a window where the refresh is silently lost —
  /// the seed alone would not reach a running client, and the client alone
  /// would be discarded by the next `subscribe()`.
  ///
  /// Does not force a reconnect: a live socket keeps running and the next
  /// connection picks the token up, so a refresh self-heals within one backoff
  /// window. Crucially it tears nothing down, so `watch` streams stay open —
  /// rebuilding the handle instead would close every stream the UI holds.
  Future<void> setToken({String? token});

  /// ADR-0029 D3: sign out — stop sync, wipe local rows AND the durable
  /// outbox (so the next principal on this device sees nothing of this one),
  /// and clear the seed token. This is the local-state wipe the other 8 SDK
  /// bindings ship; Flutter was erroneously excluded from ADR-0029 Decision 3
  /// on a `set_token`-only rationale (amended 2026-08-03) — [`Self::close`]
  /// alone does NOT wipe, so without this the prior user's rows survive in
  /// the SQLite file across a principal switch (a cross-user leak).
  ///
  /// Ordering is load-bearing and identical to the kotlin/swift ports: the
  /// connect/apply loop and every watch pump are aborted and then AWAITED
  /// (quiesced) BEFORE `clear_local_state()` runs — a post-clear apply frame
  /// would re-populate storage (the cross-user leak `clear_local_state`'s own
  /// doc warns about). [`Session`]'s `Drop` only `abort()`s these tasks (no
  /// await), so the explicit abort+await here is what guarantees quiescence
  /// precedes the wipe. Idempotent: a no-op (token clear) with no active
  /// subscription.
  ///
  /// # Errors
  /// `String` only if `clear_local_state()` itself fails (a disk error).
  Future<void> signOut();

  /// Subscribe to `tables` over ONE `/sync` WebSocket (D1/ADR-0022 multi-
  /// table-per-handle). The first entry is the primary; the rest are extra
  /// subscriptions on the same socket, all sharing one resume LSN, one
  /// checkpoint, and one ack stream (ADR-0009). Replaces any prior
  /// subscription on this handle. `state_sink` receives connection-state
  /// transitions for the life of the handle.
  ///
  /// Does NOT emit rows — call [`Self::watch`] per table to receive its row
  /// stream. (Snapshot pumps are attached separately so each table gets its
  /// own Dart stream, matching the `db.watch(table)` surface.)
  ///
  /// # Errors
  /// Returns an error string if `tables` is empty or opening the local
  /// SQLite store fails. Once subscribed, network/session errors surface
  /// only as `state_sink` transitions (reconnect is automatic and silent,
  /// matching `SyncClient::run_with_reconnect`'s contract).
  Stream<NostosConnectionState> subscribe({
    required List<TableSubFfi> tables,
    required List<String> orSetTables,
    required List<String> counterTables,
  });

  /// P5 sync streams (docs/plans/p5-sync-streams-design.md §4): subscribe to
  /// a server-defined, client-parameterized stream on the LIVE session —
  /// unlike `subscribe()`, NOTHING is torn down; the `subscribe_stream`
  /// frame goes out on the open socket (or the next reconnect if offline).
  /// Returns the client-chosen stream id for [`Self::unsubscribe_stream`].
  ///
  /// `params_json` is a JSON OBJECT string (`{"owner":"u1"}`) — the same
  /// no-codegen trick P3 used for `op` (parity plan :106). Values must be
  /// JSON scalars; the server binds them value-level into the stream's
  /// `:param` placeholders (design Decision 2 — never textual).
  ///
  /// # Errors
  /// Returns an error string if `params_json` is not a JSON object or
  /// `subscribe()` hasn't been called. Server-side rejects (unknown stream,
  /// bad params) arrive asynchronously as `stream_error` frames and are
  /// logged; they do NOT fail this call.
  Future<String> subscribeStream({
    required String name,
    required String paramsJson,
  });

  /// Drop a stream by the id [`Self::subscribe_stream`] returned. Unknown
  /// id = no-op (idempotent). v1 leaves local rows in place — eviction is
  /// separate; PowerSync behaves the same.
  ///
  /// # Errors
  /// Returns an error string if `subscribe()` hasn't been called.
  Future<void> unsubscribeStream({required String id});

  /// Attach a row stream for `table`: emits the current full row set
  /// immediately (the durable snapshot already on disk — visible offline)
  /// and again after every applied batch. One `watch` per table; `table`
  /// must be among those passed to [`Self::subscribe`]. Dropping the
  /// subscription (via `subscribe()` again or [`Self::close`]) aborts every
  /// watch pump.
  ///
  /// # Errors
  /// Returns an error string if `subscribe()` hasn't been called or `table`
  /// is not in the subscribed set.
  Stream<String> watch({required String table});

  /// Stream durable-outbox status: how many writes are queued, how many have
  /// permanently failed, and the server's message for the last permanent
  /// failure.
  ///
  /// This is the write-side counterpart to `subscribe`'s connection-state
  /// sink. Without it a Dart app cannot tell its user that a write was lost:
  /// [`Self::write`] returns once the write is durable locally, and a server
  /// rejection afterwards was previously only a `tracing` warning inside the
  /// Rust client. Flutter's own optimistic-state guidance assumes a failed
  /// write surfaces so the UI can revert; this is the signal that makes that
  /// pattern expressible on Nostos.
  ///
  /// Emits the current value immediately on subscribe (the backing channel is
  /// a `watch`, not a broadcast), so a status widget built at any point in the
  /// app's life renders the true count rather than waiting for the next
  /// change.
  ///
  /// # Errors
  /// Returns an error string if `subscribe()` hasn't been called.
  Stream<WriteQueueStatusFfi> watchWriteStatus();

  /// Enqueue a durable write against the active subscription's table.
  /// Returns once the write is captured in the local outbox (NOT once the
  /// server acks it — that happens asynchronously; the row round-trips back
  /// through `subscribe`'s `rows_sink` once applied, same as any other
  /// replicated change, per `nostos-client`'s ADR-0013 outbox contract).
  ///
  /// `op` is `"upsert"` (insert-or-update), `"delete"`, or `"patch"`
  /// (column-level UPDATE of an existing row — `payload` carries only the
  /// columns to change; P3 PowerSync PATCH parity).
  ///
  /// # Errors
  /// Returns an error string if `subscribe()` hasn't been called yet, `op`
  /// is not one of `"upsert"` / `"delete"` / `"patch"`, `table` is not in
  /// the subscribed set (see [`Self::subscribe`]), or the local durable
  /// enqueue itself failed (disk full, SQLite busy).
  Future<BigInt> write({
    required String table,
    required String op,
    required String pk,
    String? payloadJson,
  });

  /// Enqueue a batch of writes atomically (all-or-nothing outbox entry —
  /// ADR-0032 T3). All ops land in one SQLite transaction or none do. Each
  /// `NostosWriteInput` has the same fields as [`Self::write`]'s params.
  /// Returns the outbox ids in the same order as `ops`.
  ///
  /// # Errors
  /// Same preconditions as [`Self::write`] (subscribe first, valid op, table
  /// in the subscribed set). A failure on ANY op rolls back the ENTIRE batch.
  Future<Uint64List> writeBatch({required List<NostosWriteInput> ops});
}

/// Coarse connection-state signal for `Stream<NostosConnectionState>` on the
/// Dart side.
///
/// `Connected` is now a PROVEN signal, not a heuristic: it fires only when
/// `SyncClient::subscribed()` reports the session's subscribe accepted AND a
/// post-acceptance frame has arrived (snapshot boundary, replication event,
/// or write ack — see the `subscribed` field docs in nostos-client). The old
/// grace-window heuristic ("`run_once` hasn't failed within 250ms ⇒ assume
/// connected") lied exactly when it mattered: a rules-rejected subscribe
/// loop flapped `Connected` while ZERO rows ever arrived, and Dart's
/// `waitForFirstSync()` completed against a session that never synced
/// (observed 2026-08-27).
///
/// ponytail: the REJECTION reason itself still doesn't cross to Dart — the
/// loop below stops retrying on `ClientError::SubscribeRejected` (surfaces
/// as a final `Disconnected`, not a reconnect storm) and logs the reason via
/// tracing, but the enum carries no payload. Upgrade path: a
/// `NostosConnectionState::Rejected(String)` variant or a sibling error
/// stream; requires an FRB regen, deliberately deferred.
enum NostosConnectionState { connecting, connected, reconnecting, disconnected }

/// One write op inside a `write_batch` group (ADR-0032 T3). Same fields as
/// [`NostosHandle::write`]'s params.
class NostosWriteInput {
  final String table;
  final String op;
  final String pk;
  final String? payloadJson;

  const NostosWriteInput({
    required this.table,
    required this.op,
    required this.pk,
    this.payloadJson,
  });

  @override
  int get hashCode =>
      table.hashCode ^ op.hashCode ^ pk.hashCode ^ payloadJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NostosWriteInput &&
          runtimeType == other.runtimeType &&
          table == other.table &&
          op == other.op &&
          pk == other.pk &&
          payloadJson == other.payloadJson;
}

/// frb-friendly mirror of `nostos_client`'s `ClientTable` — the client-side
/// schema projection the WS2 view layer consumes. frb generates Dart bindings
/// for structs declared in THIS crate, so we mirror (rather than configuring
/// frb to reflect an external crate's type). The Dart side builds these from
/// the server's `GET /schema` `SchemaDescriptor` (drop per-column affinity down
/// to names) and hands them to [`NostosHandle::apply_schema`].
class ClientTableFfi {
  /// Canonical table id (matches `cairn_data.table_name` / the wire `table`).
  final String name;

  /// Primary-key column names (informational for the view; carried for the
  /// future materialized-table path).
  final List<String> primaryKey;

  /// Column names in tuple order.
  final List<String> columns;

  const ClientTableFfi({
    required this.name,
    required this.primaryKey,
    required this.columns,
  });

  @override
  int get hashCode => name.hashCode ^ primaryKey.hashCode ^ columns.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientTableFfi &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          primaryKey == other.primaryKey &&
          columns == other.columns;
}

/// One subscription's table spec for [`NostosHandle::subscribe`]: a table name
/// plus an optional safe-SQL `where_sql` (ADR-0012). A connection subscribes to a
/// `Vec` of these over one `/sync` socket (D1/ADR-0022 multi-table-per-handle).
class TableSubFfi {
  /// Table name to subscribe to.
  final String name;

  /// Optional safe-SQL predicate scoped to this table (ADR-0012).
  final String? whereSql;

  const TableSubFfi({required this.name, this.whereSql});

  @override
  int get hashCode => name.hashCode ^ whereSql.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableSubFfi &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          whereSql == other.whereSql;
}

/// FFI mirror of [`nostos_client::WriteQueueStatus`] — flutter_rust_bridge can
/// only generate Dart for types declared in this crate's `api` module, so the
/// engine type is re-declared here rather than re-exported.
class WriteQueueStatusFfi {
  /// Writes durably queued but not yet ack'd. `> 0` while offline is the
  /// offline-first promise working, not an error.
  final BigInt pending;

  /// Writes that permanently failed this session.
  final BigInt deadLettered;

  /// Server error text from the most recent permanent failure. Set ONLY on a
  /// dead-letter — a plain rejection is usually transient and retries, so
  /// surfacing it would train users to ignore write errors.
  final String? lastError;

  const WriteQueueStatusFfi({
    required this.pending,
    required this.deadLettered,
    this.lastError,
  });

  @override
  int get hashCode =>
      pending.hashCode ^ deadLettered.hashCode ^ lastError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WriteQueueStatusFfi &&
          runtimeType == other.runtimeType &&
          pending == other.pending &&
          deadLettered == other.deadLettered &&
          lastError == other.lastError;
}
