// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `emit_snapshot`, `hex_encode`, `row_to_json_object`, `run_connection_loop`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Session`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `drop`, `eq`, `fmt`, `fmt`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NostosHandle>>
abstract class NostosHandle implements RustOpaqueInterface {
  /// Materialize the WS2 read-views for `tables` in the on-device SQLite
  /// file (`CREATE VIEW IF NOT EXISTS <table> AS SELECT json_extract(...) AS
  /// col, ... FROM cairn_data WHERE table_name = '<table>'` — see
  /// `SqliteStorage::apply_schema`). Idempotent for an unchanged schema; the
  /// views persist in the SQLite file, so this is called ONCE after `connect`
  /// (and before the first `query()` / Dart `db.execute(SELECT ...)` that
  /// names a table).
  ///
  /// Opens a TRANSIENT storage connection at `db_path` (separate from the
  /// `subscribe` session's) purely to run the DDL, then drops it.
  /// ponytail: the transient double-open is a one-time setup cost (cheap);
  /// the upgrade path is to stash the schema on the handle and apply it
  /// inside `subscribe` on the session's own connection — deferred because
  /// this is not on any hot path.
  ///
  /// The Dart side owns the `GET /schema` fetch + `SchemaDescriptor` →
  /// `ClientTableFfi` mapping, keeping the Rust FFI crate HTTP-free
  /// (ADR-0015: no `reqwest` dep in `nostos_flutter_rust`).
  ///
  /// # Errors
  /// Returns an error string if the SQLite file can't be opened/migrated or
  /// any view DDL fails (`StorageError::Backend`).
  void applySchema({required List<ClientTableFfi> tables});

  /// Tear down the active subscription's background work — the
  /// connect/apply/reconnect loop and the watch-stream pump (see
  /// [`Session`]'s `Drop` impl, which aborts both tasks). Safe to call with
  /// no active subscription (a no-op) and safe to call more than once.
  ///
  /// Named `close`, not `dispose`: every `#[frb(opaque)]` handle already
  /// implements `RustOpaqueInterface`, which declares its own synchronous
  /// `void dispose()` for releasing the FFI handle itself — reusing that
  /// name here would collide with an unrelated method of a different
  /// signature (async vs sync). `close` mirrors `dart:io`'s
  /// `WebSocket.close()`, which this SDK's own session shape is closest to.
  ///
  /// This does NOT close the underlying SQLite file or shut down this
  /// handle's own tokio runtime — a subsequent `subscribe()` call on the
  /// SAME `NostosHandle` reopens a fresh session against the same durable
  /// store. The runtime itself is torn down when the handle is dropped
  /// (frb's generated `Drop` glue for an `#[frb(opaque)]` type, which is
  /// what `RustOpaqueInterface::dispose()` triggers), which happens once
  /// Dart releases its last reference — `close()` exists for a caller that
  /// wants to stop syncing sooner than that, e.g. a widget's `dispose()`
  /// lifecycle callback, rather than waiting on GC.
  Future<void> close();

  /// Open a connection. Does not touch the network yet — `subscribe()`
  /// starts the actual WebSocket session. `db_path` is the SQLite file the
  /// durable client state lives in (Dart picks the directory, e.g. via
  /// `path_provider`'s `getApplicationSupportDirectory()` — see the
  /// `nostos_flutter` Dart wrapper).
  static NostosHandle connect({
    required String url,
    String? token,
    required String dbPath,
  }) => RustLib.instance.api.crateApiNostosNostosHandleConnect(
    url: url,
    token: token,
    dbPath: dbPath,
  );

  /// Run an arbitrary `SELECT` against the on-device SQLite (the synced
  /// `cairn_data` table). Returns a JSON-array-of-objects STRING — one
  /// object per row, keyed by column name — which is the SAME shape the
  /// `rows` tick stream emits, so Dart decodes it identically with
  /// `jsonDecode`. The SQL typically uses
  /// `json_extract(payload, '$.col')` to project the opaque payload (JSON1
  /// ships in the bundled SQLite; ADR-0019) — e.g.
  /// `SELECT json_extract(payload, '$.title') AS title FROM cairn_data`.
  ///
  /// Requires an active subscription: the [`Session`] owns the
  /// [`SqliteStorage`] the client binds at `subscribe()` time, and
  /// `with_storage` reaches the concrete backend the same way `rows_for`
  /// does in `emit_snapshot` below (the closure param is `&SqliteStorage`,
  /// not `&Storage`, so `.query()` is callable in that position). Parity
  /// feature P1 — see `docs/plans/powersync-sdk-parity-plan.md`.
  ///
  /// This is a read-side accessor on the same `Mutex<Connection>` as the
  /// write path; it shares no mutation surface with the outbox (see the
  /// `Storage::query` doc in `nostos-core` for the trait-bound rationale).
  ///
  /// # Errors
  /// Returns an error string if `subscribe()` hasn't been called yet, the
  /// storage task panicked (`ClientError::Join`), or the SQL fails to
  /// prepare / a row fails to decode (`StorageError::Backend`).
  Future<String> query({required String sql});

  /// Subscribe to `table` (optionally filtered by `where_sql`, the safe-SQL
  /// subset ADR-0012 documents). Replaces any prior subscription on this
  /// handle. `rows_sink` receives one JSON-array string per tick — the
  /// current full row set for `table`, emitted immediately (the durable
  /// snapshot already on disk, so an offline watcher sees data right away)
  /// and again after every applied batch. `state_sink` receives connection
  /// state transitions for the life of the handle (not just this
  /// subscription — see [`NostosConnectionState`]).
  ///
  /// # Errors
  /// Returns an error string if opening the local SQLite store fails. Once
  /// subscribed, network/session errors surface only as `state_sink`
  /// transitions (reconnect is automatic and silent, matching
  /// `SyncClient::run_with_reconnect`'s contract) — `write()` is what
  /// surfaces a durable-outbox failure to the caller.
  Future<void> subscribe({
    required String table,
    String? whereSql,
    required RustStreamSink<String> rowsSink,
    required RustStreamSink<NostosConnectionState> stateSink,
  });

  /// Enqueue a durable write against the active subscription's table.
  /// Returns once the write is captured in the local outbox (NOT once the
  /// server acks it — that happens asynchronously; the row round-trips back
  /// through `subscribe`'s `rows_sink` once applied, same as any other
  /// replicated change, per `nostos-client`'s ADR-0013 outbox contract).
  ///
  /// `op` is `"upsert"` (insert-or-update), `"delete"`, or `"patch"`
  /// (column-level UPDATE of an existing row — `payload` carries only the
  /// columns to change; P3 PowerSync PATCH parity).
  ///
  /// # Errors
  /// Returns an error string if `subscribe()` hasn't been called yet, `op`
  /// is not one of `"upsert"` / `"delete"` / `"patch"`, `table` doesn't
  /// match the active subscription (v1 is one table per handle — see module
  /// docs), or the local durable enqueue itself failed (disk full, SQLite
  /// busy).
  Future<BigInt> write({
    required String table,
    required String op,
    required String pk,
    String? payloadJson,
  });
}

/// Coarse connection-state signal for `Stream<NostosConnectionState>` on the
/// Dart side.
///
/// ponytail: `Connected` is a heuristic, not a precise signal from
/// `SyncClient`. `SyncClient::run_once` blocks for the entire session
/// (connect → subscribe → apply loop) and only returns on error or a clean
/// server-initiated close — there is no mid-call hook to observe "the WS
/// handshake + subscribe succeeded" without a further `nostos-client` change,
/// which this task deliberately avoided to keep the additive surface minimal
/// (see `SyncClient::subscribe_changes` / `with_storage`, which WERE worth
/// adding). Instead: if `run_once()` hasn't already failed within a short
/// grace window (`CONNECT_GRACE`), assume the handshake succeeded — a real
/// connection refusal / DNS failure surfaces near-instantly. A slow-but-doomed
/// connect can show a brief false `Connected` before flipping to
/// `Disconnected`; acceptable for a v1 UI-facing signal. Upgrade path: add a
/// `connected`/`subscribed` broadcast to `SyncClient` alongside `changes`.
enum NostosConnectionState { connecting, connected, reconnecting, disconnected }

/// frb-friendly mirror of `nostos_client`'s `ClientTable` — the client-side
/// schema projection the WS2 view layer consumes. frb generates Dart bindings
/// for structs declared in THIS crate, so we mirror (rather than configuring
/// frb to reflect an external crate's type). The Dart side builds these from
/// the server's `GET /schema` `SchemaDescriptor` (drop per-column affinity down
/// to names) and hands them to [`NostosHandle::apply_schema`].
class ClientTableFfi {
  /// Canonical table id (matches `cairn_data.table_name` / the wire `table`).
  final String name;

  /// Primary-key column names (informational for the view; carried for the
  /// future materialized-table path).
  final List<String> primaryKey;

  /// Column names in tuple order.
  final List<String> columns;

  const ClientTableFfi({
    required this.name,
    required this.primaryKey,
    required this.columns,
  });

  @override
  int get hashCode => name.hashCode ^ primaryKey.hashCode ^ columns.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientTableFfi &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          primaryKey == other.primaryKey &&
          columns == other.columns;
}
