// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/nostos.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiNostosInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0-beta.5';

  @override
  int get rustContentHash => 1770137513;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'nostos_flutter_rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiNostosNostosHandleClose({required NostosHandle that});

  NostosHandle crateApiNostosNostosHandleConnect({
    required String url,
    String? token,
    required String dbPath,
  });

  Future<String> crateApiNostosNostosHandleQuery({
    required NostosHandle that,
    required String sql,
  });

  Future<void> crateApiNostosNostosHandleSubscribe({
    required NostosHandle that,
    required String table,
    String? whereSql,
    required RustStreamSink<String> rowsSink,
    required RustStreamSink<NostosConnectionState> stateSink,
  });

  Future<BigInt> crateApiNostosNostosHandleWrite({
    required NostosHandle that,
    required String table,
    required String op,
    required String pk,
    String? payloadJson,
  });

  Future<void> crateApiNostosInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NostosHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NostosHandle;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_NostosHandlePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiNostosNostosHandleClose({required NostosHandle that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNostosNostosHandleCloseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostosNostosHandleCloseConstMeta =>
      const TaskConstMeta(debugName: "NostosHandle_close", argNames: ["that"]);

  @override
  NostosHandle crateApiNostosNostosHandleConnect({
    required String url,
    String? token,
    required String dbPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_opt_String(token, serializer);
          sse_encode_String(dbPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNostosNostosHandleConnectConstMeta,
        argValues: [url, token, dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostosNostosHandleConnectConstMeta =>
      const TaskConstMeta(
        debugName: "NostosHandle_connect",
        argNames: ["url", "token", "dbPath"],
      );

  @override
  Future<String> crateApiNostosNostosHandleQuery({
    required NostosHandle that,
    required String sql,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
            that,
            serializer,
          );
          sse_encode_String(sql, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostosNostosHandleQueryConstMeta,
        argValues: [that, sql],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostosNostosHandleQueryConstMeta =>
      const TaskConstMeta(
        debugName: "NostosHandle_query",
        argNames: ["that", "sql"],
      );

  @override
  Future<void> crateApiNostosNostosHandleSubscribe({
    required NostosHandle that,
    required String table,
    String? whereSql,
    required RustStreamSink<String> rowsSink,
    required RustStreamSink<NostosConnectionState> stateSink,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
            that,
            serializer,
          );
          sse_encode_String(table, serializer);
          sse_encode_opt_String(whereSql, serializer);
          sse_encode_StreamSink_String_Sse(rowsSink, serializer);
          sse_encode_StreamSink_nostos_connection_state_Sse(
            stateSink,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostosNostosHandleSubscribeConstMeta,
        argValues: [that, table, whereSql, rowsSink, stateSink],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostosNostosHandleSubscribeConstMeta =>
      const TaskConstMeta(
        debugName: "NostosHandle_subscribe",
        argNames: ["that", "table", "whereSql", "rowsSink", "stateSink"],
      );

  @override
  Future<BigInt> crateApiNostosNostosHandleWrite({
    required NostosHandle that,
    required String table,
    required String op,
    required String pk,
    String? payloadJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
            that,
            serializer,
          );
          sse_encode_String(table, serializer);
          sse_encode_String(op, serializer);
          sse_encode_String(pk, serializer);
          sse_encode_opt_String(payloadJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostosNostosHandleWriteConstMeta,
        argValues: [that, table, op, pk, payloadJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostosNostosHandleWriteConstMeta =>
      const TaskConstMeta(
        debugName: "NostosHandle_write",
        argNames: ["that", "table", "op", "pk", "payloadJson"],
      );

  @override
  Future<void> crateApiNostosInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNostosInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostosInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NostosHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NostosHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  NostosHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NostosHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NostosHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NostosHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NostosHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NostosHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<NostosConnectionState>
  dco_decode_StreamSink_nostos_connection_state_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  NostosConnectionState dco_decode_nostos_connection_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NostosConnectionState.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  NostosHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NostosHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NostosHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NostosHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NostosHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NostosHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<NostosConnectionState>
  sse_decode_StreamSink_nostos_connection_state_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  NostosConnectionState sse_decode_nostos_connection_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return NostosConnectionState.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    NostosHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NostosHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    NostosHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NostosHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    NostosHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NostosHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_nostos_connection_state_Sse(
    RustStreamSink<NostosConnectionState> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_nostos_connection_state,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_nostos_connection_state(
    NostosConnectionState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class NostosHandleImpl extends RustOpaque implements NostosHandle {
  // Not to be used by end users
  NostosHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  NostosHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_NostosHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_NostosHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_NostosHandlePtr,
  );

  /// Tear down the active subscription's background work — the
  /// connect/apply/reconnect loop and the watch-stream pump (see
  /// [`Session`]'s `Drop` impl, which aborts both tasks). Safe to call with
  /// no active subscription (a no-op) and safe to call more than once.
  ///
  /// Named `close`, not `dispose`: every `#[frb(opaque)]` handle already
  /// implements `RustOpaqueInterface`, which declares its own synchronous
  /// `void dispose()` for releasing the FFI handle itself — reusing that
  /// name here would collide with an unrelated method of a different
  /// signature (async vs sync). `close` mirrors `dart:io`'s
  /// `WebSocket.close()`, which this SDK's own session shape is closest to.
  ///
  /// This does NOT close the underlying SQLite file or shut down this
  /// handle's own tokio runtime — a subsequent `subscribe()` call on the
  /// SAME `NostosHandle` reopens a fresh session against the same durable
  /// store. The runtime itself is torn down when the handle is dropped
  /// (frb's generated `Drop` glue for an `#[frb(opaque)]` type, which is
  /// what `RustOpaqueInterface::dispose()` triggers), which happens once
  /// Dart releases its last reference — `close()` exists for a caller that
  /// wants to stop syncing sooner than that, e.g. a widget's `dispose()`
  /// lifecycle callback, rather than waiting on GC.
  Future<void> close() =>
      RustLib.instance.api.crateApiNostosNostosHandleClose(that: this);

  /// Run an arbitrary `SELECT` against the on-device SQLite (the synced
  /// `cairn_data` table). Returns a JSON-array-of-objects STRING — one
  /// object per row, keyed by column name — which is the SAME shape the
  /// `rows` tick stream emits, so Dart decodes it identically with
  /// `jsonDecode`. The SQL typically uses
  /// `json_extract(payload, '$.col')` to project the opaque payload (JSON1
  /// ships in the bundled SQLite; ADR-0019) — e.g.
  /// `SELECT json_extract(payload, '$.title') AS title FROM cairn_data`.
  ///
  /// Requires an active subscription: the [`Session`] owns the
  /// [`SqliteStorage`] the client binds at `subscribe()` time, and
  /// `with_storage` reaches the concrete backend the same way `rows_for`
  /// does in `emit_snapshot` below (the closure param is `&SqliteStorage`,
  /// not `&Storage`, so `.query()` is callable in that position). Parity
  /// feature P1 — see `docs/plans/powersync-sdk-parity-plan.md`.
  ///
  /// This is a read-side accessor on the same `Mutex<Connection>` as the
  /// write path; it shares no mutation surface with the outbox (see the
  /// `Storage::query` doc in `nostos-core` for the trait-bound rationale).
  ///
  /// # Errors
  /// Returns an error string if `subscribe()` hasn't been called yet, the
  /// storage task panicked (`ClientError::Join`), or the SQL fails to
  /// prepare / a row fails to decode (`StorageError::Backend`).
  Future<String> query({required String sql}) =>
      RustLib.instance.api.crateApiNostosNostosHandleQuery(that: this, sql: sql);

  /// Subscribe to `table` (optionally filtered by `where_sql`, the safe-SQL
  /// subset ADR-0012 documents). Replaces any prior subscription on this
  /// handle. `rows_sink` receives one JSON-array string per tick — the
  /// current full row set for `table`, emitted immediately (the durable
  /// snapshot already on disk, so an offline watcher sees data right away)
  /// and again after every applied batch. `state_sink` receives connection
  /// state transitions for the life of the handle (not just this
  /// subscription — see [`NostosConnectionState`]).
  ///
  /// # Errors
  /// Returns an error string if opening the local SQLite store fails. Once
  /// subscribed, network/session errors surface only as `state_sink`
  /// transitions (reconnect is automatic and silent, matching
  /// `SyncClient::run_with_reconnect`'s contract) — `write()` is what
  /// surfaces a durable-outbox failure to the caller.
  Future<void> subscribe({
    required String table,
    String? whereSql,
    required RustStreamSink<String> rowsSink,
    required RustStreamSink<NostosConnectionState> stateSink,
  }) => RustLib.instance.api.crateApiNostosNostosHandleSubscribe(
    that: this,
    table: table,
    whereSql: whereSql,
    rowsSink: rowsSink,
    stateSink: stateSink,
  );

  /// Enqueue a durable write against the active subscription's table.
  /// Returns once the write is captured in the local outbox (NOT once the
  /// server acks it — that happens asynchronously; the row round-trips back
  /// through `subscribe`'s `rows_sink` once applied, same as any other
  /// replicated change, per `nostos-client`'s ADR-0013 outbox contract).
  ///
  /// `op` is `"upsert"` (insert-or-update) or `"delete"`.
  ///
  /// # Errors
  /// Returns an error string if `subscribe()` hasn't been called yet, `op`
  /// is neither `"upsert"` nor `"delete"`, `table` doesn't match the active
  /// subscription (v1 is one table per handle — see module docs), or the
  /// local durable enqueue itself failed (disk full, SQLite busy).
  Future<BigInt> write({
    required String table,
    required String op,
    required String pk,
    String? payloadJson,
  }) => RustLib.instance.api.crateApiNostosNostosHandleWrite(
    that: this,
    table: table,
    op: op,
    pk: pk,
    payloadJson: payloadJson,
  );
}
