// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/nostos.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiNostosInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0-beta.5';

  @override
  int get rustContentHash => 1298625975;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'nostos_flutter_rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiNostosNostosHandleApplySchema({
    required NostosHandle that,
    required List<ClientTableFfi> tables,
  });

  Future<void> crateApiNostosNostosHandleClose({required NostosHandle that});

  NostosHandle crateApiNostosNostosHandleConnect({
    required String url,
    String? token,
    required String dbPath,
  });

  Future<void> crateApiNostosNostosHandleDisconnect({required NostosHandle that});

  Future<String> crateApiNostosNostosHandleQuery({
    required NostosHandle that,
    required String sql,
  });

  Stream<NostosConnectionState> crateApiNostosNostosHandleResume({
    required NostosHandle that,
  });

  Future<void> crateApiNostosNostosHandleSetToken({
    required NostosHandle that,
    String? token,
  });

  Future<void> crateApiNostosNostosHandleSignOut({required NostosHandle that});

  Stream<NostosConnectionState> crateApiNostosNostosHandleSubscribe({
    required NostosHandle that,
    required List<TableSubFfi> tables,
  });

  Stream<String> crateApiNostosNostosHandleWatch({
    required NostosHandle that,
    required String table,
  });

  Stream<WriteQueueStatusFfi> crateApiNostosNostosHandleWatchWriteStatus({
    required NostosHandle that,
  });

  Future<BigInt> crateApiNostosNostosHandleWrite({
    required NostosHandle that,
    required String table,
    required String op,
    required String pk,
    String? payloadJson,
  });

  Future<void> crateApiNostosInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NostosHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NostosHandle;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_NostosHandlePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiNostosNostosHandleApplySchema({
    required NostosHandle that,
    required List<ClientTableFfi> tables,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
            that,
            serializer,
          );
          sse_encode_list_client_table_ffi(tables, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostosNostosHandleApplySchemaConstMeta,
        argValues: [that, tables],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostosNostosHandleApplySchemaConstMeta =>
      const TaskConstMeta(
        debugName: "NostosHandle_apply_schema",
        argNames: ["that", "tables"],
      );

  @override
  Future<void> crateApiNostosNostosHandleClose({required NostosHandle that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNostosNostosHandleCloseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostosNostosHandleCloseConstMeta =>
      const TaskConstMeta(debugName: "NostosHandle_close", argNames: ["that"]);

  @override
  NostosHandle crateApiNostosNostosHandleConnect({
    required String url,
    String? token,
    required String dbPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_opt_String(token, serializer);
          sse_encode_String(dbPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNostosNostosHandleConnectConstMeta,
        argValues: [url, token, dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostosNostosHandleConnectConstMeta =>
      const TaskConstMeta(
        debugName: "NostosHandle_connect",
        argNames: ["url", "token", "dbPath"],
      );

  @override
  Future<void> crateApiNostosNostosHandleDisconnect({required NostosHandle that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostosNostosHandleDisconnectConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostosNostosHandleDisconnectConstMeta =>
      const TaskConstMeta(
        debugName: "NostosHandle_disconnect",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiNostosNostosHandleQuery({
    required NostosHandle that,
    required String sql,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
            that,
            serializer,
          );
          sse_encode_String(sql, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostosNostosHandleQueryConstMeta,
        argValues: [that, sql],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostosNostosHandleQueryConstMeta =>
      const TaskConstMeta(
        debugName: "NostosHandle_query",
        argNames: ["that", "sql"],
      );

  @override
  Stream<NostosConnectionState> crateApiNostosNostosHandleResume({
    required NostosHandle that,
  }) {
    final stateSink = RustStreamSink<NostosConnectionState>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
              that,
              serializer,
            );
            sse_encode_StreamSink_nostos_connection_state_Sse(
              stateSink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 6,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiNostosNostosHandleResumeConstMeta,
          argValues: [that, stateSink],
          apiImpl: this,
        ),
      ),
    );
    return stateSink.stream;
  }

  TaskConstMeta get kCrateApiNostosNostosHandleResumeConstMeta =>
      const TaskConstMeta(
        debugName: "NostosHandle_resume",
        argNames: ["that", "stateSink"],
      );

  @override
  Future<void> crateApiNostosNostosHandleSetToken({
    required NostosHandle that,
    String? token,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
            that,
            serializer,
          );
          sse_encode_opt_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNostosNostosHandleSetTokenConstMeta,
        argValues: [that, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostosNostosHandleSetTokenConstMeta =>
      const TaskConstMeta(
        debugName: "NostosHandle_set_token",
        argNames: ["that", "token"],
      );

  @override
  Future<void> crateApiNostosNostosHandleSignOut({required NostosHandle that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostosNostosHandleSignOutConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostosNostosHandleSignOutConstMeta =>
      const TaskConstMeta(
        debugName: "NostosHandle_sign_out",
        argNames: ["that"],
      );

  @override
  Stream<NostosConnectionState> crateApiNostosNostosHandleSubscribe({
    required NostosHandle that,
    required List<TableSubFfi> tables,
  }) {
    final stateSink = RustStreamSink<NostosConnectionState>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
              that,
              serializer,
            );
            sse_encode_list_table_sub_ffi(tables, serializer);
            sse_encode_StreamSink_nostos_connection_state_Sse(
              stateSink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 9,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiNostosNostosHandleSubscribeConstMeta,
          argValues: [that, tables, stateSink],
          apiImpl: this,
        ),
      ),
    );
    return stateSink.stream;
  }

  TaskConstMeta get kCrateApiNostosNostosHandleSubscribeConstMeta =>
      const TaskConstMeta(
        debugName: "NostosHandle_subscribe",
        argNames: ["that", "tables", "stateSink"],
      );

  @override
  Stream<String> crateApiNostosNostosHandleWatch({
    required NostosHandle that,
    required String table,
  }) {
    final rowsSink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
              that,
              serializer,
            );
            sse_encode_String(table, serializer);
            sse_encode_StreamSink_String_Sse(rowsSink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 10,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiNostosNostosHandleWatchConstMeta,
          argValues: [that, table, rowsSink],
          apiImpl: this,
        ),
      ),
    );
    return rowsSink.stream;
  }

  TaskConstMeta get kCrateApiNostosNostosHandleWatchConstMeta =>
      const TaskConstMeta(
        debugName: "NostosHandle_watch",
        argNames: ["that", "table", "rowsSink"],
      );

  @override
  Stream<WriteQueueStatusFfi> crateApiNostosNostosHandleWatchWriteStatus({
    required NostosHandle that,
  }) {
    final statusSink = RustStreamSink<WriteQueueStatusFfi>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
              that,
              serializer,
            );
            sse_encode_StreamSink_write_queue_status_ffi_Sse(
              statusSink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 11,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiNostosNostosHandleWatchWriteStatusConstMeta,
          argValues: [that, statusSink],
          apiImpl: this,
        ),
      ),
    );
    return statusSink.stream;
  }

  TaskConstMeta get kCrateApiNostosNostosHandleWatchWriteStatusConstMeta =>
      const TaskConstMeta(
        debugName: "NostosHandle_watch_write_status",
        argNames: ["that", "statusSink"],
      );

  @override
  Future<BigInt> crateApiNostosNostosHandleWrite({
    required NostosHandle that,
    required String table,
    required String op,
    required String pk,
    String? payloadJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
            that,
            serializer,
          );
          sse_encode_String(table, serializer);
          sse_encode_String(op, serializer);
          sse_encode_String(pk, serializer);
          sse_encode_opt_String(payloadJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostosNostosHandleWriteConstMeta,
        argValues: [that, table, op, pk, payloadJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostosNostosHandleWriteConstMeta =>
      const TaskConstMeta(
        debugName: "NostosHandle_write",
        argNames: ["that", "table", "op", "pk", "payloadJson"],
      );

  @override
  Future<void> crateApiNostosInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNostosInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostosInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NostosHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NostosHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  NostosHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NostosHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NostosHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NostosHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NostosHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NostosHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<NostosConnectionState>
  dco_decode_StreamSink_nostos_connection_state_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<WriteQueueStatusFfi>
  dco_decode_StreamSink_write_queue_status_ffi_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  NostosConnectionState dco_decode_nostos_connection_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NostosConnectionState.values[raw as int];
  }

  @protected
  ClientTableFfi dco_decode_client_table_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ClientTableFfi(
      name: dco_decode_String(arr[0]),
      primaryKey: dco_decode_list_String(arr[1]),
      columns: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ClientTableFfi> dco_decode_list_client_table_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_client_table_ffi).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TableSubFfi> dco_decode_list_table_sub_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_table_sub_ffi).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  TableSubFfi dco_decode_table_sub_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TableSubFfi(
      name: dco_decode_String(arr[0]),
      whereSql: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WriteQueueStatusFfi dco_decode_write_queue_status_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return WriteQueueStatusFfi(
      pending: dco_decode_u_64(arr[0]),
      deadLettered: dco_decode_u_64(arr[1]),
      lastError: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  NostosHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NostosHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NostosHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NostosHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NostosHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NostosHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<NostosConnectionState>
  sse_decode_StreamSink_nostos_connection_state_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<WriteQueueStatusFfi>
  sse_decode_StreamSink_write_queue_status_ffi_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  NostosConnectionState sse_decode_nostos_connection_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return NostosConnectionState.values[inner];
  }

  @protected
  ClientTableFfi sse_decode_client_table_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_primaryKey = sse_decode_list_String(deserializer);
    var var_columns = sse_decode_list_String(deserializer);
    return ClientTableFfi(
      name: var_name,
      primaryKey: var_primaryKey,
      columns: var_columns,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ClientTableFfi> sse_decode_list_client_table_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ClientTableFfi>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_client_table_ffi(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TableSubFfi> sse_decode_list_table_sub_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TableSubFfi>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_table_sub_ffi(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TableSubFfi sse_decode_table_sub_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_whereSql = sse_decode_opt_String(deserializer);
    return TableSubFfi(name: var_name, whereSql: var_whereSql);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WriteQueueStatusFfi sse_decode_write_queue_status_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pending = sse_decode_u_64(deserializer);
    var var_deadLettered = sse_decode_u_64(deserializer);
    var var_lastError = sse_decode_opt_String(deserializer);
    return WriteQueueStatusFfi(
      pending: var_pending,
      deadLettered: var_deadLettered,
      lastError: var_lastError,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    NostosHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NostosHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    NostosHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NostosHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNostosHandle(
    NostosHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NostosHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_nostos_connection_state_Sse(
    RustStreamSink<NostosConnectionState> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_nostos_connection_state,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_write_queue_status_ffi_Sse(
    RustStreamSink<WriteQueueStatusFfi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_write_queue_status_ffi,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_nostos_connection_state(
    NostosConnectionState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_client_table_ffi(
    ClientTableFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_list_String(self.primaryKey, serializer);
    sse_encode_list_String(self.columns, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_client_table_ffi(
    List<ClientTableFfi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_client_table_ffi(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_table_sub_ffi(
    List<TableSubFfi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_table_sub_ffi(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_table_sub_ffi(TableSubFfi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.whereSql, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_write_queue_status_ffi(
    WriteQueueStatusFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.pending, serializer);
    sse_encode_u_64(self.deadLettered, serializer);
    sse_encode_opt_String(self.lastError, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class NostosHandleImpl extends RustOpaque implements NostosHandle {
  // Not to be used by end users
  NostosHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  NostosHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_NostosHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_NostosHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_NostosHandlePtr,
  );

  /// Materialize the WS2 read-views for `tables` in the on-device SQLite
  /// file (`CREATE VIEW IF NOT EXISTS <table> AS SELECT json_extract(...) AS
  /// col, ... FROM cairn_data WHERE table_name = '<table>'` — see
  /// `SqliteStorage::apply_schema`). Idempotent for an unchanged schema; the
  /// views persist in the SQLite file, so this is called ONCE after `connect`
  /// (and before the first `query()` / Dart `db.execute(SELECT ...)` that
  /// names a table).
  ///
  /// Opens a TRANSIENT storage connection at `db_path` (separate from the
  /// `subscribe` session's) purely to run the DDL, then drops it.
  /// ponytail: the transient double-open is a one-time setup cost (cheap);
  /// the upgrade path is to stash the schema on the handle and apply it
  /// inside `subscribe` on the session's own connection — deferred because
  /// this is not on any hot path.
  ///
  /// The Dart side owns the `GET /schema` fetch + `SchemaDescriptor` →
  /// `ClientTableFfi` mapping, keeping the Rust FFI crate HTTP-free
  /// (ADR-0015: no `reqwest` dep in `nostos_flutter_rust`).
  ///
  /// # Errors
  /// Returns an error string if the SQLite file can't be opened/migrated or
  /// any view DDL fails (`StorageError::Backend`).
  void applySchema({required List<ClientTableFfi> tables}) => RustLib
      .instance
      .api
      .crateApiNostosNostosHandleApplySchema(that: this, tables: tables);

  /// Tear down the active subscription's background work — the
  /// connect/apply/reconnect loop and every watch pump (see [`Session`]'s
  /// `Drop` impl, which aborts all of them). Safe to call with no active
  /// subscription (a no-op) and safe to call more than once.
  ///
  /// Named `close`, not `dispose`: every `#[frb(opaque)]` handle already
  /// implements `RustOpaqueInterface`, which declares its own synchronous
  /// `void dispose()` for releasing the FFI handle itself — reusing that
  /// name here would collide with an unrelated method of a different
  /// signature (async vs sync). `close` mirrors `dart:io`'s
  /// `WebSocket.close()`, which this SDK's own session shape is closest to.
  ///
  /// This does NOT close the underlying SQLite file or shut down this
  /// handle's own tokio runtime — a subsequent `subscribe()` call on the
  /// SAME `NostosHandle` reopens a fresh session against the same durable
  /// store. The runtime itself is torn down when the handle is dropped
  /// (frb's generated `Drop` glue for an `#[frb(opaque)]` type, which is
  /// what `RustOpaqueInterface::dispose()` triggers), which happens once
  /// Dart releases its last reference — `close()` exists for a caller that
  /// wants to stop syncing sooner than that, e.g. a widget's `dispose()`
  /// lifecycle callback, rather than waiting on GC.
  Future<void> close() =>
      RustLib.instance.api.crateApiNostosNostosHandleClose(that: this);

  Future<void> disconnect() =>
      RustLib.instance.api.crateApiNostosNostosHandleDisconnect(that: this);

  /// Run an arbitrary `SELECT` against the on-device SQLite (the synced
  /// `cairn_data` table). Returns a JSON-array-of-objects STRING — one
  /// object per row, keyed by column name — which is the SAME shape the
  /// `rows` tick stream emits, so Dart decodes it identically with
  /// `jsonDecode`. The SQL typically uses
  /// `json_extract(payload, '$.col')` to project the opaque payload (JSON1
  /// ships in the bundled SQLite; ADR-0019) — e.g.
  /// `SELECT json_extract(payload, '$.title') AS title FROM cairn_data`.
  ///
  /// Requires an active subscription: the [`Session`] owns the
  /// [`SqliteStorage`] the client binds at `subscribe()` time, and
  /// `with_storage` reaches the concrete backend the same way `rows_for`
  /// does in `emit_snapshot` below (the closure param is `&SqliteStorage`,
  /// not `&Storage`, so `.query()` is callable in that position). Parity
  /// feature P1 — see `docs/plans/powersync-sdk-parity-plan.md`.
  ///
  /// This is a read-side accessor on the same `Mutex<Connection>` as the
  /// write path; it shares no mutation surface with the outbox (see the
  /// `Storage::query` doc in `nostos-core` for the trait-bound rationale).
  ///
  /// # Errors
  /// Returns an error string if `subscribe()` hasn't been called yet, the
  /// storage task panicked (`ClientError::Join`), or the SQL fails to
  /// prepare / a row fails to decode (`StorageError::Backend`).
  Future<String> query({required String sql}) =>
      RustLib.instance.api.crateApiNostosNostosHandleQuery(that: this, sql: sql);

  /// Resume syncing after [`disconnect`]: respawn the connect/apply/reconnect
  /// loop on the SAME `SyncClient` (reusable across aborts — `run_once(&self)`,
  /// all per-session state local, `tokio::sync::Mutex` carries no poison). The
  /// durable outbox drains on the new session's startup flush; live updates
  /// resume. `state_sink` receives the fresh run's transitions
  /// (`connecting → connected → …`). Requires a prior `subscribe()`.
  ///
  /// Named `resume`, not `connect`: the `#[frb(sync)]` constructor is already
  /// `NostosHandle::connect`, and Rust forbids two inherent items of the same
  /// name; the Dart public API mirrors the pause/resume pair (WS5) for the
  /// same reason — `connect` clashes with `Nostos.connect`/`NostosDatabase.connect`.
  Stream<NostosConnectionState> resume() =>
      RustLib.instance.api.crateApiNostosNostosHandleResume(that: this);

  /// Pause syncing: abort ONLY the connect/apply/reconnect loop, keeping the
  /// `SyncClient`, its `SqliteStorage`, and every `watch()` pump alive. Reads,
  /// writes (which land in the durable outbox), and the UI keep working
  /// offline. `resume()` restarts it. Idempotent: a no-op when already paused
  /// or when there is no active subscription.
  ///
  /// Emits nothing on `state_sink` here (the aborted loop leaves it mid
  /// `connecting`/`reconnecting`); the Dart wrapper surfaces `disconnected`
  /// so the UI signal has one owner. Cancellation is task-abort: `run_once`
  /// respects no stop token, and `tokio::sync::Mutex` (no poison) + `Arc`
  /// client state mean the client stays usable for local work after the abort.
  /// Replace the bearer token for subsequent connections (ADR-0010 auth).
  ///
  /// Call this when the auth provider rotates a token — for `supabase_flutter`
  /// that is `onAuthStateChange` firing `tokenRefreshed`. Without it a client
  /// keeps re-sending the token it was constructed with, the server rejects it
  /// on `exp`, and the reconnect loop retries a dead credential forever: the
  /// app renders stale rows and never syncs again.
  ///
  /// Updates BOTH the handle's seed (so a later `subscribe()` builds its config
  /// with the new value) and the live `SyncClient` if a session already exists.
  /// Missing either half leaves a window where the refresh is silently lost —
  /// the seed alone would not reach a running client, and the client alone
  /// would be discarded by the next `subscribe()`.
  ///
  /// Does not force a reconnect: a live socket keeps running and the next
  /// connection picks the token up, so a refresh self-heals within one backoff
  /// window. Crucially it tears nothing down, so `watch` streams stay open —
  /// rebuilding the handle instead would close every stream the UI holds.
  Future<void> setToken({String? token}) => RustLib.instance.api
      .crateApiNostosNostosHandleSetToken(that: this, token: token);

  /// ADR-0029 D3: sign out — stop sync, wipe local rows AND the durable
  /// outbox (so the next principal on this device sees nothing of this one),
  /// and clear the seed token. This is the local-state wipe the other 8 SDK
  /// bindings ship; Flutter was erroneously excluded from ADR-0029 Decision 3
  /// on a `set_token`-only rationale (amended 2026-08-03) — [`Self::close`]
  /// alone does NOT wipe, so without this the prior user's rows survive in
  /// the SQLite file across a principal switch (a cross-user leak).
  ///
  /// Ordering is load-bearing and identical to the kotlin/swift ports: the
  /// connect/apply loop and every watch pump are aborted and then AWAITED
  /// (quiesced) BEFORE `clear_local_state()` runs — a post-clear apply frame
  /// would re-populate storage (the cross-user leak `clear_local_state`'s own
  /// doc warns about). [`Session`]'s `Drop` only `abort()`s these tasks (no
  /// await), so the explicit abort+await here is what guarantees quiescence
  /// precedes the wipe. Idempotent: a no-op (token clear) with no active
  /// subscription.
  ///
  /// # Errors
  /// `String` only if `clear_local_state()` itself fails (a disk error).
  Future<void> signOut() =>
      RustLib.instance.api.crateApiNostosNostosHandleSignOut(that: this);

  /// Subscribe to `tables` over ONE `/sync` WebSocket (D1/ADR-0022 multi-
  /// table-per-handle). The first entry is the primary; the rest are extra
  /// subscriptions on the same socket, all sharing one resume LSN, one
  /// checkpoint, and one ack stream (ADR-0009). Replaces any prior
  /// subscription on this handle. `state_sink` receives connection-state
  /// transitions for the life of the handle.
  ///
  /// Does NOT emit rows — call [`Self::watch`] per table to receive its row
  /// stream. (Snapshot pumps are attached separately so each table gets its
  /// own Dart stream, matching the `db.watch(table)` surface.)
  ///
  /// # Errors
  /// Returns an error string if `tables` is empty or opening the local
  /// SQLite store fails. Once subscribed, network/session errors surface
  /// only as `state_sink` transitions (reconnect is automatic and silent,
  /// matching `SyncClient::run_with_reconnect`'s contract).
  Stream<NostosConnectionState> subscribe({required List<TableSubFfi> tables}) =>
      RustLib.instance.api.crateApiNostosNostosHandleSubscribe(
        that: this,
        tables: tables,
      );

  /// Attach a row stream for `table`: emits the current full row set
  /// immediately (the durable snapshot already on disk — visible offline)
  /// and again after every applied batch. One `watch` per table; `table`
  /// must be among those passed to [`Self::subscribe`]. Dropping the
  /// subscription (via `subscribe()` again or [`Self::close`]) aborts every
  /// watch pump.
  ///
  /// # Errors
  /// Returns an error string if `subscribe()` hasn't been called or `table`
  /// is not in the subscribed set.
  Stream<String> watch({required String table}) => RustLib.instance.api
      .crateApiNostosNostosHandleWatch(that: this, table: table);

  /// Stream durable-outbox status: how many writes are queued, how many have
  /// permanently failed, and the server's message for the last permanent
  /// failure.
  ///
  /// This is the write-side counterpart to `subscribe`'s connection-state
  /// sink. Without it a Dart app cannot tell its user that a write was lost:
  /// [`Self::write`] returns once the write is durable locally, and a server
  /// rejection afterwards was previously only a `tracing` warning inside the
  /// Rust client. Flutter's own optimistic-state guidance assumes a failed
  /// write surfaces so the UI can revert; this is the signal that makes that
  /// pattern expressible on Nostos.
  ///
  /// Emits the current value immediately on subscribe (the backing channel is
  /// a `watch`, not a broadcast), so a status widget built at any point in the
  /// app's life renders the true count rather than waiting for the next
  /// change.
  ///
  /// # Errors
  /// Returns an error string if `subscribe()` hasn't been called.
  Stream<WriteQueueStatusFfi> watchWriteStatus() =>
      RustLib.instance.api.crateApiNostosNostosHandleWatchWriteStatus(that: this);

  /// Enqueue a durable write against the active subscription's table.
  /// Returns once the write is captured in the local outbox (NOT once the
  /// server acks it — that happens asynchronously; the row round-trips back
  /// through `subscribe`'s `rows_sink` once applied, same as any other
  /// replicated change, per `nostos-client`'s ADR-0013 outbox contract).
  ///
  /// `op` is `"upsert"` (insert-or-update), `"delete"`, or `"patch"`
  /// (column-level UPDATE of an existing row — `payload` carries only the
  /// columns to change; P3 PowerSync PATCH parity).
  ///
  /// # Errors
  /// Returns an error string if `subscribe()` hasn't been called yet, `op`
  /// is not one of `"upsert"` / `"delete"` / `"patch"`, `table` is not in
  /// the subscribed set (see [`Self::subscribe`]), or the local durable
  /// enqueue itself failed (disk full, SQLite busy).
  Future<BigInt> write({
    required String table,
    required String op,
    required String pk,
    String? payloadJson,
  }) => RustLib.instance.api.crateApiNostosNostosHandleWrite(
    that: this,
    table: table,
    op: op,
    pk: pk,
    payloadJson: payloadJson,
  );
}
