// =============================================================================
// @nostos-sync/react-native Android library — the Wave-B Kotlin TurboModule that
// backs Wave-A's `NativeNostos.ts` Codegen spec.
// -----------------------------------------------------------------------------
// Reuses `sdk/nostos_kotlin` WHOLESALE:
//   - the already-shipped `libnostos_kotlin.so` (aarch64-linux-android) lives in
//     `src/main/jniLibs/arm64-v8a/` (copied by scripts/build-android.sh);
//   - the UniFFI-generated Kotlin sources (`uniffi.nostos_kotlin.NostosClient`)
//     live in `src/main/kotlin-uniffi/` (regenerated by scripts/build-android.sh
//     via `uniffi-bindgen generate --language kotlin`).
// No Rust is forked or rebuilt here — this module wraps the UniFFI handle in a
// hand-written Codegen-shaped TurboModule (`NativeNostosSpec` + `NostosTurboModule`)
// and exposes the 5 Spec methods (connect / subscribe / write / query /
// checkpoint) to JS.
//
// Build shape mirrors nostos_kotlin/android/build.gradle.kts so the JNA + NDK +
// AGP versions stay single-sourced across the two Android SDKs.
// =============================================================================
plugins {
    // AGP 9 ships built-in Kotlin; applying org.jetbrains.kotlin.android on
    // top is rejected by the new DSL —
    // developer.android.com/build/migrate-to-built-in-kotlin
    id("com.android.library") version "9.4.1"
}

android {
    namespace = "run.nostos.reactnative"
    compileSdk = 36

    defaultConfig {
        minSdk = 24

        // instrumented-test runner — needed for connectedDebugAndroidTest.
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        // Live-E2E port plumbing (parity with nostos_kotlin): the on-device
        // `live_connect_push_echo_roundTrip` test reads the host-side spine's
        // port from this instrumentation arg. The orchestrator
        // (scripts/run-android-e2e.sh) passes it via
        // `./gradlew connectedDebugAndroidTest -PnostosPort=<port>`; "0" = unset
        // → the live test self-skips via assumeTrue (offline test still runs).
        testInstrumentationRunnerArguments["nostosPort"] =
            (project.findProperty("nostosPort") ?: "0").toString()
    }

    sourceSets {
        getByName("main") {
            // Hand-written TurboModule Kotlin under src/main/kotlin (default).
            // UniFFI-generated Kotlin (`uniffi.nostos_kotlin.NostosClient`) under
            // src/main/kotlin-uniffi — output dir of `uniffi-bindgen generate`
            // in scripts/build-android.sh. Default `src/main/java` is also kept.
            // `kotlin.srcDirs`, not `java.srcDirs` — AGP 9 built-in Kotlin only
            // reads the kotlin source set (see nostos_kotlin for the failure mode).
            kotlin.srcDirs("src/main/kotlin", "src/main/kotlin-uniffi")
            // .so bundle — copied by scripts/build-android.sh from
            // target/aarch64-linux-android/debug/libnostos_kotlin.so (stripped).
            jniLibs.srcDirs("src/main/jniLibs")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }


    // .so inside the .aar — keep nostos_kotlin's packaging choice so the test
    // app loads the .so the same way the shipped .aar does.
    packaging {
        jniLibs {
            useLegacyPackaging = false
        }
    }

    testOptions {
        targetSdk = 36
    }
}

dependencies {
    // React Native public API surface (ReactContextBaseJavaModule, ReactMethod,
    // Promise, ReactPackage). Since RN 0.71 the android artifact is on Maven
    // Central as `com.facebook.react:react-android`; depending on it directly
    // avoids needing the RN gradle plugin / codegen task to run in this
    // standalone library build. Pinned to the peer-dep version declared in
    // package.json (react-native >=0.79).
    implementation("com.facebook.react:react-android:0.79.7")

    // UniFFI 0.28's Kotlin runtime dispatches FFI through JNA. JNA 5.16.0 is
    // required on Android 15+ / 16KB-page devices (libjnidispatch.so alignment)
    // — same rationale as nostos_kotlin/android/build.gradle.kts.
    implementation("net.java.dev.jna:jna:5.16.0@aar")
    // Expose JNA to the instrumented-test classloader — the test apk needs
    // JNA's classes + libjnidispatch.so on ITS classpath, not just the
    // library-under-test's.
    androidTestImplementation("net.java.dev.jna:jna:5.16.0@aar")

    // Instrumented test deps — connectedDebugAndroidTest runner.
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test:runner:1.5.2")
}
